apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: litellm-postgres
  namespace: litellm
spec:
  instances: 1

  storage:
    size: 1Gi
    storageClass: "longhorn-ha-2"

  template:
    metadata:
      labels:
        recurring-job.longhorn.io/source: "enabled"
        recurring-job-group.longhorn.io/backup: "enabled"

  bootstrap:
    initdb:
      database: litellm
      owner: litellm
