apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: volcano
  namespace: volcano-system
spec:
  interval: 5m
  chart:
    spec:
      chart: volcano
      version: '1.13.0'
      sourceRef:
        kind: HelmRepository
        name: volcano-repo
        namespace: flux-system
      interval: 5m
  values:
    # https://github.com/volcano-sh/volcano/blob/master/installer/helm/chart/volcano/values.yaml
    basic:
      image_pull_policy: "Always"
    custom:
      # don't deploy it's own standalone Grafana metrics tracking
      metrics_enable: false
