---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: steam-analysis-isthereanydeal-secret
  namespace: steam-analysis
spec:
  encryptedData:
    ISTHEREANYDEAL_API_KEY: AgAU6ATdRUyebI3n4bQM5QNPIzBumDKY9rjtulww6ORrGcdcRG7EDrgiigIMUsEEQMQluERQ//28busBmMqFVT1U+g0jdsvKKgZR8LEcib+a1YSI5j88VEHIAfmgBQJQIjlGli3W8fQ6LtLpNR/By7x6LZqhu713+3QCxMlRkR7nNRs4Fw5Z6GokcVGJf/KCCsb1TJ6CSKzHMIF+HKmw/mamzVGtrJ3qYtyDWmEzG5sJFX3FZRUq83qA6Zh7i9BB/leQp5PhWdd0n5cdKqAi8T91uYJnGRK7VPyaw8/B9QYfWnqio98GTQGJ9D8eLk5g1BSBNFVyKVxIbLTZbxiV7GYXHM6grvLEBM45eRMYpH0kYvGYJ3B3dikVE1G1EmvRkKfkjzdVJjxl1AbzihXN4QJSEOoAG2BseZ01vrC/pm7Xofl1A7vL7jyRdWEW7cftZKEEG89Yw5/03/w3Y1+mScni4+FylMQenGOQtFOvELrxVT1Ks5UN5mELsj0tdUe8HZdbeUh3qKtbedAzoW71iUNKnk0bvgJqoB10wl42NJhAxa2GqUEJvu2hlyU97eOs3PKxFnUsPuFRVqMH8Rg1f9eQoaH6sayugzAVQdHxwP51VTjgTTbjFNck4tDR0+y/czTD3+ClQFXGSMaZ8ouBtzEaNj760d6PH0WB+E+ChVnpmpg7VAizfNtjC5nXhxX+U6UfXUR6pXhmPtAS4ta4UaISmg5uNgamClXbaAEiYUpD3jGpeUNOezY9
  template:
    metadata:
      name: steam-analysis-isthereanydeal-secret
      namespace: steam-analysis
    type: Opaque
