---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: steam-analysis-twitch-secret
  namespace: steam-analysis
spec:
  encryptedData:
    TWITCH_CLIENT_ID: AgCiRgvQazde/0GFZY2rb6+Sdn1idf9Wqb77sZVwgK29Szdna5XeZvzFrWCGF9cbhOFcQjHXtEdyb9eXSk5dX0woimixLNd6LfcMdBNOe1IMNG/IcB66jzUoZBAxvcyP28y2F7bK6GguUZHCybpzermWlRrd7iYWTG4If/hHOhDZmzQpMADynwCBAEw3GCTM5tyaen2dWoddGcr3VXVCfABX/KOQ+M2eITlKw0YMSQisFQQB94eMnVWvlsk7ixxhjnvmS2U4+svYAI9CaQSA4MR+/QuU3XJySDlfucuWf7FD8hR3Ryfk1KJlkKnzitRz0sFJamK7PLfMzwhb4qm6Ejmmx8/6ANPQP7jmmn4tnb8w6/PfCCicO4Lqnh03lOwKW6+tvJo6aa9pu9Pyt/RinbzDVDQpgxcvp9AakXde0Eoi+85/smDrhSaVJwhRWH6OzWFg2NDa6DvOu/HVESLt6gyjHcA4AMQVssxeqoMz3XBrnmW8wrGM+0GTD6T7GnWDt7QEkOHLtbpR1C55lKQ+X6uujZPJYI8T3lpeK4wws3ySMMcnwjinXnbTfo4/dvM+k8SzEBn1fBFEHxl2Gtv7m5jEd9ZKiJJ2qstzq8Dxky/Sp+goMYT47AJuhHj9c9R09uOa0SrSMUyR3TLIZQeWLdIMQ7kyQRv1OZlYcA5s7okqsD5nUycOXGTJ7txhrbzWzVckOi5n8cuJx8KrFFyM9fZpbp7ovvV2QLzeS/2g/nQ=
    TWITCH_CLIENT_SECRET: AgCOytDO1Toix/axIHY06kb941QmVHD+E54LeLPnXHDJNedqr/dAd2rmNdxjerm9fvSFfW6VprF1CYOCkrkFSxuXZQIBDBzbNB63SxqRNmWTF55VoGTTRAB+ySmgevCwxhAHUoOb8CROz/VRbcmvkGFBgOMiF5dSO6D1nR6bYCbVNtymzjpMR3+mnf4lVe+KV50TXMslUqAn5mr8WxvM7PXgKnRfIeuq0kwHvwrUk0PpGTmOWheX45bBLQZ/S/+ezCPpSacF6z68coPMUaHwQQLR1V/bw6vYIt4twkUbK3jr26gLxpZM0PQe+cTk7NG1kbkv50prMsiCJJAuezmDSyZAktRzDkLEveB697aWAEr2OOyjXSJ1oXMuUaVzIc44q7+DBrllkIh5jPby49VW4kzzx39K55E+YIPqJg2GRaY8unapTXXAGwj29SrUeuAfrhgKU4cPfOfa3M/s+UXJfrR8eGl6RY+eWhzltrQYjglG0JA1y94bB57QXRZGcYyZXwqyUju85DfJWV4q5BJ5OSV/J85RhbFB+NbChrIg7MVXO9/oVtVuMOySuh3HrNbj5A16ojwiXkoxrkuVjRLwJ2Hf8Nvrh2Roi9bjoiYKNJze/1ymEGeCYrQJqc+LeLYwrsRd46sfDXeimQNkkbcG7vzqymd+w/IDAhJRnoiUQdQc3z6589Hee5R7ISHMQMEMTyZm19j+ZEIvOyPuA6ehrFo+Lx94Fl80JA5Wokp3/lQ=
  template:
    metadata:
      name: steam-analysis-twitch-secret
      namespace: steam-analysis
    type: Opaque
