apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: steam-analysis-mongodb-ingressroute
  namespace: steam-analysis
spec:
  entryPoints:
    - mongodb
  routes:
    - match: HostSNI(`*`)
      services:
        - name: steam-analysis-mongodb
          port: 27017
