---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: steam-analysis-steamapi-secret
  namespace: steam-analysis
spec:
  encryptedData:
    STEAM_API_KEY: AgB6luYx2Cnj1fG0pw0ZeJIPtqwUzrM+XwUzugSnQ/lZNHMJFJlsAlwfrbmS6CN00pT5dkRY0BcHiPH3DPONVCvlrdGhsZ1jmrxpoZAL1LhuyioUs1QFbiND2eFkBk270GagRinOuUFaq7T4IjftVhaqlAx4s5VniG+KLv/AKomhh8kg3eSYcio0uNNJhMXYiKTgKv0yVC+YXiTdtfibHLs2GZy0GCwht8dBmoRiwD3tjBKk5SCRDdf54WMUPWuvhxrjGORcL789vIiWMCdEv2kTMINev5dlGTwfkiKQ7/1PC+LfaDKP1+7R7XY93KNOQhPb7w2cF6sx/4CsupQlQ9G36S616NJJ9533SS20C2VSBBsEprlNPNkK94yqBvOhZ4yFYV0g6zJzU4IuUG+IT8qu5LHbXmiszGMK8RTGlwMatolQt3pWGTmEGNgJeXrr2aXs5QyGTQWZUUP2nKrzyTqkKEu2JAj7/HGroK43ySivJ5xpwOvOUS2TRDV4YR/yfL37fhDEaGnsWS5MfrGETpqGrtbG6WFPjjfF1CTZ8OmRWd5yNIECIK/GSOGph1u9fDhPxEhN5euVAbHztaZWTb4AUrtOxOnf/xpGSGo26DxfPDlzJzRKmz++KcdKdDvlzlhembnuVZ6c5cM7yBps8R7PRnYt26YmgEQC56/hSAa5UrRYcCCgfL3XQslqaIu/OankpeGyFRb+x/PYoFM77j1FaIlwaDSkoEiPIvaOdTMCew==
  template:
    metadata:
      name: steam-analysis-steamapi-secret
      namespace: steam-analysis
    type: Opaque
