---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: steam-analysis-mongo-secret
  namespace: steam-analysis
spec:
  encryptedData:
    MONGO_INITDB_ROOT_PASSWORD: AgCGadKJtUX8QI7EC/RJcpVH/hWr9trS1uxH42dHg4dHK8oTaELUAnz68GOdiAHA90uDQVA5JAQnCC6Ux0DIqPHyzORKpFG1GKpzz6I5BNr+VyuW0g2/0Hq00+8qsv+lIX/AJC4fHWNaHqNEabHS+Ls/wv7mmbWI2YPJUzcT9eMTNs12M4eWktpbso+qUtWpDcqQWw9aD7l1Uil0LEhTSXkzRcfWHi+nXzUx3l7HsrimxLRIKLVDhct2yE9Say5A2xJR+nytpeV4NwJ8FS/l6hh1t8CAGbQtiZ/3U+1AfPg7aMFQ2dsSTuOpWlKGmw6kXJzv4QNHwDICm/LLd/KU3nXfiG9D5W9K3FL+/OnwI175Bv15/I+CmfKpQpM5yMqWwYjV/rXwZhDkiv3NprKORrutxEOIkyeNvkUXh/rIqVSDEIO+RUne1BKr5az6wo7lhJt7SSbeazHM8kS4f6E96sKHqxrT3dZVnw5vlJT06V5WkQCaH+8WH6haA16PMvU+a3e+mV5fXQEfNDFnVd/qTBWoXzJJgKgK/aOXBYRUay6vadbCNocg6xcGcllK7NvHLNqTk1YlPjSs8+x1DxWLp8E5knaTnBGw+D7BKF/Xbi54WoGmqvPNHxEXqEPHrgEPAL51RAYSFpStxSbZbtrvGer1GVTUF+0ypGcMnYbRGiYLlpvPPfG84iacXSWsNXGTPx7Ko3K8T/r1Dw==
  template:
    metadata:
      name: steam-analysis-mongo-secret
      namespace: steam-analysis
    type: Opaque
