---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: steam-analysis-mongo-password-secret
  namespace: steam-analysis
spec:
  encryptedData:
    MONGO_INITDB_ROOT_PASSWORD: AgBXjdlocz3eWJZGe6agJLJ4bqVRLKcMt03Y7rTV+nd6AVjxSmHc6rmJ56chTSqpdsw4cnxRiC6ssGS+HHQvxWAH49zzMt8pX9RHv/o17qe8MtDs/4LT0J++lIEli+p9AbuNKwI+R37TQrPaT5kLbTC+Ib9zYGv6g0f2E1t5FOZ5N58vxsFMPCwCO1uWfa6tRbGAMB/sunXSZTG5W2U+qyhbH3ouuRkfSp/PjdMpqDO61FSapYYgbgVfZx/46OutVHrdyGVmcZdTY70+Z0pSu3CxGzDgi3f4CRZrce4aJN+xwAvexOPyxO6PobOwOY7InJ1HTjAAOPBVV2eud1lv/S8l+OpaHfr5FJJlV0GED2vEjcI8mhRtaO7HI+bpO4fWi7HsWJBoPCVqt9fVBvkxS47wMwGvoLhdByQt5Pof5IeJX/jApjc4Vv1xuroDjeB6rVBGgD6yQsK154nYRMXrgFLVcGckGrp15G0tRQqSQhe9SUOIyn17OYxO7hQiK437SDrlpv5nklgMAWRaCRiHw6lOzW0If6P+FFTJAOKdJA6mOVhsHpZp2HsVdVUNkT1ms5Igz1GXYhdMZiUt20YO/ozsT4O30I43KQGzTHvTvFsyl9VqqwqK0glX/RTv/py18UJMUKdt5gX8IwsImjaenbw9tusxko3utLyYvaXr14XV3cndCheCeg6i6agg1tH/Ro4nhTDqa3qvjg==
  template:
    metadata:
      name: steam-analysis-mongo-password-secret
      namespace: steam-analysis
    type: Opaque
