apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trivy-defectdojo
  namespace: trivy-defectdojo
spec:
  interval: 5m
  chart:
    spec:
      chart: trivy-dojo-report-operator
      # https://github.com/telekom-mms/trivy-dojo-report-operator/tree/main
      version: '0.8.6'
      sourceRef:
        kind: HelmRepository
        name: trivy-defectdojo
        namespace: flux-system
      interval: 5m
  # https://github.com/DefectDojo/django-DefectDojo/blob/master/helm/defectdojo/values.yaml
  values:
    defectDojoApiCredentials:
      createSecret: true
      apiKey: "YOUR_DEFECTDOJO_API_KEY"
      url: "YOUR_DEFECTDOJO_URL"
