apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 5m
  chart:
    spec:
      chart: authentik
      # https://charts.goauthentik.io/index.yaml
      version: '2025.6.2'
      sourceRef:
        kind: HelmRepository
        name: authentik-repo
        namespace: flux-system
      interval: 5m
  # https://github.com/goauthentik/helm/blob/main/charts/authentik/values.yaml
  values:
    server:
      metrics:
        enabled: true
    authentik:
      secret_key: "secret"
      # This sends anonymous usage-data, stack traces on errors and
      # performance data to sentry.io, and is fully opt-in
      error_reporting:
        enabled: false
      postgresql:
        password: "secret"
    postgresql:
      enabled: true
      auth:
        password: "secret"
    redis:
      enabled: true
    global:
      envFrom:
        - secretRef:
          name: authentik-akadmin-credentials
