apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 5m
  chart:
    spec:
      chart: authentik
      # https://charts.goauthentik.io/index.yaml
      version: '2025.2.1'
      sourceRef:
        kind: HelmRepository
        name: authentik-repo
        namespace: flux-system
      interval: 5m
  # https://github.com/goauthentik/helm/blob/main/charts/authentik/values.yaml
