apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 5m
  chart:
    spec:
      chart: authentik
      # https://coredns.github.io/helm/index.yaml
      version: '1.38.1'
      sourceRef:
        kind: HelmRepository
        name: authentik-repo
        namespace: flux-system
      interval: 5m
  # https://github.com/coredns/helm/blob/master/charts/coredns/values.yaml
  values:
    service:
      type: LoadBalancer
