apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: authentik-config
  namespace: authentik
spec:
  interval: 10m
  path: ./configs/
  prune: true
  dependsOn:
    - name: authentik
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
