apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: memos
  namespace: memos
spec:
  interval: 5m
  chart:
    spec:
      chart: memos
      sourceRef:
        kind: GitRepository
        name: memos
        namespace: flux-system
      interval: 5m
  # https://github.com/usememos/helm/blob/main/values.yaml
  values:
    image:
      tag: "0.28.0"
