apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus-cert
  namespace: prometheus
spec:
  secretName: prometheus-certificate-secret
  dnsNames:
    - "prometheus.homelab.rivetcode.com"
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
