apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: config-metallb-system
  namespace: flux-system
spec:
  interval: 15m
  dependsOn:
  - name: metallb-metallb-system
  path: ./clusters/home/configs/metallb/
  prune: true # remove any elements later removed from the above path
  timeout: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
  retryInterval: 1m
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: metallb-controller
      namespace: metallb-system
