apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: config-traefik
  namespace: kube-system
spec:
  interval: 15m
  dependsOn:
  - name: metallb
  path: ./configs/traefik/
  prune: true # remove any elements later removed from the above path
  timeout: 2m
  sourceRef:
    kind: GitRepository
    name: traefik-configs
  retryInterval: 1m
