apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: metube
  namespace: flux-system
spec:
  interval: 5m
  url: oci://oci.trueforge.org/truecharts/metube
  ref:
    tag: 2026.04.28
