apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: karakeep
  namespace: karakeep
spec:
  interval: 5m
  chart:
    spec:
      chart: karakeep
      version: '0.32.0'
      sourceRef:
        kind: HelmRepository
        name: karakeep
        namespace: flux-system
      interval: 5m
  # https://github.com/karakeep-app/helm-charts/blob/main/charts/karakeep/values.yaml
  values:
    applicationProtocol: https
    applicationHost: karakeep.homelab.rivetcode.com
    meilisearch:
      auth:
        existingMasterKeySecret: "{{ .Release.Name }}-meilesearch"
      environment:
        MEILI_ENV: production
        # https://www.meilisearch.com/docs/resources/help/telemetry#environment-variable
        # turn off telemetry
        MEILI_NO_ANALYTICS: true
      persistence:
        enabled: true
        size: 1Gi
        storageClass: "longhorn-ha-2"
        labels:
          recurring-job.longhorn.io/source: enabled
          recurring-job-group.longhorn.io/backup: enabled
    secrets:
      karakeep:
        enabled: false
    controllers:
      karakeep:
        containers:
          karakeep:
            envFrom:
              - secretRef:
                  name: karakeep-oauth-oidc-secret
            env:
              # OLLAMA_BASE_URL: "https://ollama.homelab.rivetcode.com"
              # INFERENCE_TEXT_MODEL: "qwen3.5:0.8b"
              # INFERENCE_JOB_TIMEOUT_SEC: "120"
              DISABLE_PASSWORD_AUTH: "true"
              OAUTH_ALLOW_DANGEROUS_EMAIL_ACCOUNT_LINKING: "true"
              OAUTH_AUTO_REDIRECT: "true"
              EMAIL_VERIFICATION_REQUIRED: "false"
              OAUTH_PROVIDER_NAME: Authentik
              OAUTH_SCOPE: openid email profile
              OAUTH_WELLKNOWN_URL: https://authentik.homelab.rivetcode.com/application/o/karakeep/.well-known/openid-configuration
        statefulset:
          volumeClaimTemplates:
            - name: data
              accessMode: ReadWriteOnce
              size: 2Gi
              globalMounts:
                - path: /data
              storageClass: "longhorn-ha-2"
              labels:
                recurring-job.longhorn.io/source: enabled
                recurring-job-group.longhorn.io/backup: enabled
