---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-authentik-oauth
  namespace: grafana
spec:
  encryptedData:
    client_id: AgDRQBvAXsIUWAr396p4oRh1x/bIWzRh2In5Vnqh5YpX1ORS+nBhMplKS369HavGPY+LWBoTzV1O8fhfJFNlS1k6hH8OiyzsBmxTMsCGJMqgUAe3dmpSN4ELQoawCWYfo97lBF+n8mh9PPbvEHXi+M9zX+IUaUamOgwua2Ibh9Rge/IVwqvjALnrNvUJlVC56K2f9/gHeNoqjdtlQiSUGqUKObuUoSl/ug4LMBZh05hHI2b3muSZQq138je8D/N7/edQ4bpyz3AIqRYF9pC33H9X1JI5t3irtQ75eok9F34uG1g1ZslotHBhgOm1yMHrQ+z7Ny3njG0sglA8ssPxHFs7cPMEExsqPIHYHF8o51LmpXyrkO1WzH1aDBkEWsaAcxEDlq9Mz/WJk/+n7rRZH7xloYj3SlnUNSGR5Ptg2ZlGXVX8VGm4mkHCI4QDso1x+JZ0+ZYzcCpkJRhGy4YI9iEVOoGlzi4sIoejyyb37ncw1MD2rZX3P0BNsdnsdlZbRzJsrqwXUfJzLZ1LxL5mUC3hhnj8QvsXUoZs9XPBMffzUVakfPZA6W9Dj4/igpMDUsZ5cXAjuF+8p+HK0B4dqRd2CFILyAqqgOLj0qqWsjKYUVaGAPnN9kjKKQVnU9ihveuENh4QBqKDnEppkto6B4QWZWiHS8Az4wBUE1EeJISfm2UQMuv2yxaZNG8dzp+xFlp0KZ8IYbIZU1gdhDHxp7Pj4YM4OjhIdXbc/cD+NLXW6OZZrhrDHxE8
    client_secret: AgAObs/cH6ROMjNmdsB5CSoJuTFFOV6dqB1UOcAv4RLPepSnLcKu/BxFGyhsqiYNfj7Q7hQVr00W0GPLzyAaQXvIIS4tq6OX6NT0k7nNaiBl3Px2OGLYmV2X6mIDCV5kQfxp/fTE1yn1zNccBgwHcAuR40tS5CbGs+qNG0ZaSCRYTbcNwmJigIARxXqGw02unE2RlVtp7xc5oKxNHKBOa/7gWtl6az1wzdlVsJX+5PDwH32TdV9ko81uRfDnFnUXChwXCAzs+SpkUIY9/4b+9vfxWtgZaIwh9Ggf9jMLJ8HoQHPW4Se0cUE0/T9ZftUODyfdd5EqQw5us5YH+/MvuOUvfbSUPxeJaqn7ALTUvGgqYK79k2ynN5TIwyzD3qFaXnxTUBK28fooGg2fjKPMjgL0thy3ZVZwE3Kkk5CURprpWWGpfojODd/LKZM7uaVKorzhBHFMW2d1aVmkX7m+Vw6i1wdpbqOqB5yu9C8wZq6PanNXOxKSOybPAhIk8byGNEES+IjM3jZTwytdL3Np5lsmIi2WcB42604MuhTuqZHdQ0+bxUr27k6rb30jlP9IrbuoWt6XVgG55IYYEbsc3zyeLsWO+zQ6AQlGdLvVb/OONt6j+Rkm9hKSNh8Q5OKKH1dRiaTJWsgpMe56rAfTSxij/UmUDM6irErmSlbAps7Sf0uLgIQM4FC4OYM8LhhdjgRh10w8czKVZBNA+ck12+0r7Vwqh96vw1/dyWSQDOOZ4Dwmx1YseU4H5U+oIzP+FUavZc9RUCxoMjPqqtBG2aY26r+2L14mG/253I+C9AehEl9+XscQN4SadWuvLvb8b0ouGHi9QYF2A6uSNNwreD+XpH17eUlQIhA/eKLmiflE7g==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-authentik-oauth
      namespace: grafana
    type: Opaque
