---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-authentik-oauth
  namespace: grafana
spec:
  encryptedData:
    OAUTH_CLIENT_ID: AgB7wZpKOPE7OFAxTrmqHGmTGCO/1y/3bA/VuvJKv5q6W9Az7qSigcHxSxiJtYYEbPeP+sVN1l2MZEao0vLpwccAu6qm6s0bfcC/6jKGfUFtg4HzB/HK3hqsIsKdSHaHUfhjHVeoeAfyzYe3KPZLF8vgLL/sl47fCK1o0VDfwgFl/pAkN4xljfDG4XjVkDZgr41m1bSt3O6zTiU9jBfC95VFWGO/Qathv0kRtjiMlS++io2XlxC5t/pZ5hTgi74ENOXR9S/95aKIn+iLY6staxESGLUYOoPEizcrnlsWwQBCpnsobopt28LVot/fd8rLxT19S1NDKx5zAOtHbhdbaqtm0aaZi4jKxUI5NIhM1CtqvfFwE0Mozk3u/qLz2cYm5ljGSe8qrX5TYV22R3UBABUWFmzarVvn+iNWrrIWnsuC/DzNqNq6wOsGAFmJMHfBd2NiSS2KtVvxFPFL8mH/JmdURwqlJbUBUeZI6XZ3g5ppHhQVIRRSLkbF4MbRevvEHS9iKCcNlxQ/ErnqLt6wvBm8Sm3kzgxpA2ki8Au47C+Cgo+gVpPuoJzVVm/zy0TpTbI6PbluyRB5X/j14niHBSrXKATh15U2wqotXXW9mLIhyg32NVFAoZ1k/Ov/uNDGd+C3l29cNHo+x0J2jfq1dwzLIWp3o2igkeXvzhg3VbovDk8hZhdoK56z6Xgp/VIWurBhswkQfPFpo/pATBGqXI0F6yGBa8y9B9Mu+eqdzulekSprz381gmOC
    OAUTH_CLIENT_SECRET: AgA4AVgJClKGkfc5sIMWnQ4jTwO6DiGf1e3BwSL2bUmu2+H+oM1BlfzXeJhEbxjZZxW+5zA+LfmsbWB5gcqV31cDEsALXosZHRpMkxy7HIh8JAHE8kvrAEoWAs4CVaYpfPnUrNRubiqyZJzQp0OxkjR82UU9K9ZOgoPsR/V1bNTlh4or1tbkLAJ7VoaZiAXBfbFNhrx8BRZBU+zI1tDduIqASyYA9HVKw2/GttSj6/XyI0ntyHHflcDE6QzGKnKXrdBOKOrbyZtCaUpB6lVJNfYppc/Ix6cQLV+9lbks/zcJ/PfQElemvxg6GpYHgXaHbNq438kfarnKHz4NIc47IHe0cNWjw5sfHaddXT61AjtEumtpOQM0ru8d0OeGIXP68IoIaWVk9lf2E/tj/Hah5hCDI8Pn8vT7TqbkfGleo77m8duAIl5JlPJTEmhCgQlYF7aAS/Tsm9Z1eGN0gg4B5BhUJq/8dX8T2xtteBk5IiYB9YaIgpB1X0cytT7+WZgej3f4bP6N1Iv5475Ugi1nHvFMvltnHo/V5xwUY+5TTY+ZP/GhgR+REc60VQeVd5xvjaQjaR8l4by9z1UgscjSfWF+fG3WZ3+tWPAkEQv22kK63P0MSoW4a6viQAYfVfKCC+7uciwJfsGbp6M4MH5DQ+5wDE3JJuUNtfJXiIhKlxrH8/EUwYY3QagH5uZZlGaThBTTnMJZ3EhgO5ZRKbANxRrpMaYe7kok2ssqlODUTeEAZru0phHrdXwtuAGh8SC0MCKgVLMemFF4xtbZtrkNCebp1yQ0LnnEvKtJ9Dv1Q0mCXwW4jq9LT8N48ywsH9p4W3+j3T36LLR0yFDf8/ukW/Sx1p30mmbL1aEaPzVxLT/ZNq7w63CgPAeAnWnjyK9RCjU4sQnlLsbukNRdacSk+qcZHBaIvde8swEOZcEIGiXPT+g7Iw2XCEjmwnTeWj4BZOfIAXQ0iYZp9hSCdaAgawrJmSnyZDCPJAa6XF2IYkvn61HZU0D6lI+0kutAsn6p5BPPii8/dC8YDXFtkatrhvXW
  template:
    metadata:
      creationTimestamp: null
      name: grafana-authentik-oauth
      namespace: grafana
    type: Opaque
