apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: stirlingpdf
  namespace: stirlingpdf
spec:
  interval: 5m
  chart:
    spec:
      chart: stirlingpdf
      # https://aquasecurity.github.io/helm-charts/index.yaml
      # https://docs.stirlingpdf.com/Installation/Kubernetes%20Install
      # https://github.com/Stirling-Tools/Stirling-PDF-chart/tree/main/charts/stirling-pdf
      version: '2.0.2'
      sourceRef:
        kind: HelmRepository
        name: stirlingpdf
        namespace: flux-system
      interval: 5m
  install:
    crds: CreateReplace
  # https://github.com/Stirling-Tools/Stirling-PDF-chart/blob/main/charts/stirling-pdf/values.yaml
  values:
    serviceMonitor:
      # for prometheus metrics
      enabled: true
