apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
  namespace: headlamp
spec:
  interval: 5m
  chart:
    spec:
      chart: headlamp
      # https://kubernetes-sigs.github.io/headlamp/index.yaml
      version: '0.38.0'
      sourceRef:
        kind: HelmRepository
        name: headlamp
        namespace: flux-system
      interval: 5m
  # https://github.com/kubernetes-sigs/headlamp/blob/main/charts/headlamp/values.yaml
  values:
    service:
      type: LoadBalancer
    config:
      oidc:
        secret:
          create: false
        externalSecret:
          enabled: true
          name: headlamp-authentik-oauth
    serviceAccount:
      create: false
      name: headlamp
    volumes:
      - name: headlamp-kubeconfig
        secret:
          secretName: headlamp-kubeconfig
          items:
            - key: config
              path: config
    volumeMounts:
      - name: headlamp-kubeconfig
        mountPath: /home/headlamp/.config/Headlamp/kubeconfigs
        readOnly: true
