apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
  namespace: headlamp
spec:
  interval: 5m
  chart:
    spec:
      chart: headlamp
      # https://headlamp-k8s.github.io/headlamp/index.yaml
      version: '0.30.1'
      sourceRef:
        kind: HelmRepository
        name: headlamp
        namespace: flux-system
      interval: 5m
  # https://github.com/headlamp-k8s/headlamp/blob/main/charts/headlamp/values.yaml
  values:
    service:
      type: LoadBalancer
