apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: litellm
  namespace: litellm
spec:
  interval: 5m
  chart:
    spec:
      chart: ./deploy/charts/litellm-helm
      sourceRef:
        kind: GitRepository
        name: litellm
        namespace: flux-system
      interval: 5m
  # https://github.com/BerriAI/litellm/blob/litellm_internal_staging/deploy/charts/litellm-helm/values.yaml
  values:
    image:
      # Use "ghcr.io/berriai/litellm-database" for optimized image with database
      # we have a standalone postgres database so we don't need that
      repository: harbor.homelab.rivetcode.com/ghcr-proxy/berriai/litellm
      pullPolicy: IfNotPresent
      tag: v1.91.0
    environmentSecrets:
      - litellm-oauth-oidc-secret
      - litellm-gemini-api-key-secret
      - litellm-cerebras-api-key-secret
    envVars:
      # https://docs.litellm.ai/docs/proxy/admin_ui_sso
      GENERIC_AUTHORIZATION_ENDPOINT: "https://authentik.homelab.rivetcode.com/application/o/authorize/"
      GENERIC_TOKEN_ENDPOINT: "https://authentik.homelab.rivetcode.com/application/o/token/"
      GENERIC_USERINFO_ENDPOINT: "https://authentik.homelab.rivetcode.com/application/o/userinfo/"
      AUTO_REDIRECT_UI_LOGIN_TO_SSO: "true"
      PROXY_BASE_URL: "https://litellm.homelab.rivetcode.com"
      # https://docs.litellm.ai/docs/proxy/admin_ui_sso#set-proxy-admin
      PROXY_ADMIN_ID: "akadmin"
      # force to only use config.yaml file for model setup
      STORE_MODEL_IN_DB: "false"
    db:
      deployStandalone: false
      # kubectl get clusters -n litellm
      useExisting: true
      endpoint: litellm-postgres-rw.litellm.svc.cluster.local
      database: litellm
      secret:
        name: litellm-postgres-app
        usernameKey: username
        passwordKey: password
    proxy_config:
      model_list:
        # At least one model must exist for the proxy to start
        - model_name: gemini-2.5-flash-lite
          litellm_params:
            model: gemini/gemini-2.5-flash-lite
            api_key: os.environ/GEMINI_API_KEY
        - model_name: gemma-4-31b-it
          litellm_params:
            model: gemini/gemma-4-31b-it
            api_key: os.environ/GEMINI_API_KEY
        - model_name: gemma-4-26b-a4b-it
          litellm_params:
            model: gemini/gemma-4-26b-a4b-it
            api_key: os.environ/GEMINI_API_KEY
        - model_name: gpt-oss-120b
          litellm_params:
            model: cerebras/gpt-oss-120b
            api_key: os.environ/CEREBRAS_API_KEY
      general_settings:
        master_key: os.environ/PROXY_MASTER_KEY
