apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: litellm
  namespace: litellm
spec:
  interval: 5m
  chart:
    spec:
      chart: oci://docker.litellm.ai/berriai/litellm-helm
      version: 0.1.2
      sourceRef:
        kind: HelmRepository
        name: litellm
        namespace: flux-system
      interval: 5m
  # https://github.com/BerriAI/litellm/blob/litellm_internal_staging/deploy/charts/litellm-helm/values.yaml
  values:
    image:
      # Use "ghcr.io/berriai/litellm-database" for optimized image with database
      repository: harbor.homelab.rivetcode.com/ghcr-proxy/berriai/litellm-database
