apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: litellm
  namespace: litellm
spec:
  interval: 5m
  chart:
    spec:
      chart: ./deploy/charts/litellm-helm
      sourceRef:
        kind: GitRepository
        name: litellm
        namespace: flux-system
      interval: 5m
  # https://github.com/BerriAI/litellm/blob/litellm_internal_staging/deploy/charts/litellm-helm/values.yaml
  values:
    image:
      # Use "ghcr.io/berriai/litellm-database" for optimized image with database
      repository: harbor.homelab.rivetcode.com/ghcr-proxy/berriai/litellm-database
    environmentSecrets:
      - litellm-oauth-oidc-secret
    envVars:
      # https://docs.litellm.ai/docs/proxy/admin_ui_sso
      GENERIC_AUTHORIZATION_ENDPOINT: "https://authentik.homelab.rivetcode.com/application/o/authorize/"
      GENERIC_TOKEN_ENDPOINT: "https://authentik.homelab.rivetcode.com/application/o/token/"
      GENERIC_USERINFO_ENDPOINT: "https://authentik.homelab.rivetcode.com/application/o/userinfo/"
      AUTO_REDIRECT_UI_LOGIN_TO_SSO: "true"
    db:
      deployStandalone: false
      # kubectl get clusters -n litellm
      useExisting: true
      endpoint: litellm-postgres-rw.litellm.svc.cluster.local
      database: litellm
      secret:
        name: litellm-postgres-app
        usernameKey: username
        passwordKey: password
