---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rabbitmq-secret
  namespace: rabbitmq
spec:
  encryptedData:
    password: AgBydP6rKikDuCWPM2TWu9MeZ9ELcNSteomTU5r7CpEAWOA2yNGFnmB7ThEYgczhjEfTGWVJz5Lf1zo8uWOr2nxSMwN66G9YM5SKZoej6x+fDaWLrelQIpcyTmrSSSQWgEcgaAFMJTnKOYqc1YjRZxhKZ6IpA6hyk/bmNx66eQYm9r3rz34atkPsf6e2+xoc50QCugpJGAvRNX1oS2K4iZprJav7gZIpCvQg4hf/314UlgTvrBvti0a34rUquwfMas+QTqJMAIGYeXMSRspG/chYT6c1ZfAy8a32KaVTMfaJzVmiH4i57m/iuyil4l1Qa7oRsXQQE4wf7049f4cPws9t/h9xMU8XLCpFoAbiLzh3YvOFAPZOVQNUbD7aTBOpdbD+20saG58aBQe50BFq3FHo5GCpnwn80c5qYTvEitkQpTKfNCVqpc6QGUjppXMofrlLA2O+oka+/npfiWgrZoYZ1hcFps07IZAsCMw8GdFLurTW5WcTVqAj6SDdT5OEPT5i5WnuKpou0WAY4sOvSxr8IR/bAWnquw1xVtIsYSaJrSjb+Eq6w5QCRWkG61f9ugpHpc4S2Dxyo3V/C9Eb0qIzJOmoZI6WPNXvj6/9nlDszoVbrbwMcn7TI0GeWbj/w98qBPkWjBw4h1FMGJdt2v0hbabW3Cu4FhaF4JNkhpBKKSL4ZUr5Ii5X8dRxzd1LbMIeS/DeNcsYOw==
    username: AgCvMSY0JtsxU71QcXdOLH05ZDyUY7BL6pIG16rRSF8mAVtIDqj6JhgbSkesi3/KXwtfRddx4D9QLzVq9Qr7QUUjUmcpBjkh/tfHTQ2nomPpm5UFniw95yv9RLNoXRzbJc16zhX7+0A04IHLht/1qnpuHSDFm8iXlo15d04GtTi0ZqU7jeHq5ZgRGIrTF6JsMUvszzCWWlI516xkrwOvvBoi42WqojDWzjO4GnbE9ar2DPKPiV3HCl5HoVZUT5g2KXBb6Kqpa0FCIyvAGc0arggtw6Zs1KrCGi4vwOf4KwBr2aHOz4kTi4em28+SHdbkeiAXCzMI3jMfOS3e/8BpXdMFJe4qhCuS9XS2sHhIZzKX34QOLxRI3b40t2WwtnLBxE7JZYHA5yVTI8iQBOSqZqsDpwg4p9Uq3h0vpRXQklGRSmwHFNx3ljhFL5LPYr/GPRyXxtmKpRlfW8ZfkrU5wlczzSAq24r0g8bFwcE8JE4d+TkLXoJ5Hd38aZLS0VlhxCqI2FXVVWE1yaNUBg5J6YoAlMKkKtMLZOW606UGtJgWBfdKfQmubJztM9KM4rBQUjMmCPrgmPtDqOUctNUmuh9Tp+2VOgbvCAMcI53IhIzH8nv2ooAai687pRW2AlIBKB2wP8SQdt2FF4WH2KcaLSVhwWUxsWTl9sKFmn+8rc3ndbCKSL0GGVcQ1WllVA8xudeBrX8lLsZjZw==
  template:
    metadata:
      name: rabbitmq-secret
      namespace: rabbitmq
    type: Opaque
