---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rabbitmq-authentik-oauth
  namespace: rabbitmq
spec:
  encryptedData:
    OAUTH_CLIENT_ID: AgATm0vOzo7qeXvz1vhP+JQJqBip5W+4fmldMdC7MpOzmU4jlJgy1a2Scy2FF/mmpqH3UbgLL77EQdIyCZn/Jx9F46YhbNbmhWYRJWQeaMAZ6dpxshq+rZkPcZ6sORSEDexzZdI4SSHvHIa4gJtPFAQQTUuSrIBvTjDb6HgoyZ3bG0Lpb8E7ckansv2V9K84Lg4oeD5NB1vhGUZdH3CqFvHIA3PJ2HiNIFfjvyOVGd0dkTwYDGdbq6rCJT4OjaUPipVrYGFcMEZaEI2S9qynYvfXiuFlESmhXn2qtLu2E6qC+20LKokYqc4YYt5vEJrxwn596lVBLuPX0l+LlpCiHHAnXmpsIziC5hyNiFPiwHUzhdpSVSY8ftv9L6j5oKSF9IGgHbcGSLfxkcLs2Z3hk1lOgkspbaUjJBOFG8rd+oVj2zTzdxWOil+nUVIl1yGvI3oIiySGdFYJ7lCckEyfs84QvFUyg75b/e7jTEFDDXhw/p4H0wuP4SkLuXEesKd/96hI+TkMiI0d2bw2VNGRGlN94JRqqqmz641oEYr+qMyN98spePUA4IQb633sGU3T5kW4wbcDRzY8JEchmKRoTSHscTazTeEpEtYgH2ChoFmAA0xxrI8FRbR9hrualxU5MtAxDMBkVTRQgPt3KVy1Df7aq8JVX5zRHeieF0amqn3EbYXJ8iKBkeyLw7RPYW64DQAjlCTwI5dS5HWjzWwKj8x+Jt1meRNpFFaP/vlthlQYdo68zKD5p/gp
    OAUTH_CLIENT_SECRET: AgBkx//q0HaEHXDUfPaU0kMX2szpnHT5hanFncIv82qKUtH6fYqIf4b/yzGuil7jG6l+D4G/ZC0SskecVAFtGE8NyhDH5lAtvB9gCWN+UrsTRgpynoWZi8I7BuTI5FAVLhztsuZmztgGiX/pMyRtxQuxGNtxu/ZpRnr0OxIDYppHKAUlbebTWomAsnCdZyzl0F5h4vA1AsMj35Q5XQbJgaFe6He28NTJHdq69pISu6zIT+QsoaPepU8952Sp/LTTunSUHn9YYRNh+ZJ02XMaSqkf+auqAIASs18vMoSJtKAzWC3D7caQSmaWIPR7ysifwy/J1eWhXBA41yWggEmQYBsOsEeSK9nWC21l171nYXPVW0O4TarUaouUzCmM5yA/wiBhEp+4GOBb6y0jZih9rGtxpHPVivcifS7bNiaeKI9JRx36QovzGQESyW5b/r/sH2bK3pMeHyZoYQVx0LXHccZTFAP3fkeW45YuOAQjUvnwa1xQrrkM6tbFnrX8OWGPUWBw9yOrhr8DcFMZyOq32BTVZ0HaPMrOse3NYpNIgHlJKYCg5OC8fet+nOu/eXCtgfSNHv7oKCQM+hKjp3wsKOjhcXplY14Hm2d4i2NriRLnBPWPO3erjYpglgpmqxL2q0fb262oIxP7Q5fK+anvIwg38xSg9951qy25b1tp/RUiaOA+d3JXDJQN9v61AnDGNT/Rs6G5S6BrAIWIWRdG8WTMA/amWN0z2QTnmSGcPHHaoAumWfDxzIJddE4y2oRNawfq5PzjjNI0XqV9rpyZTgfzAJ43HGaCnQOXXSBmc5Dy6WGasGvCa1rAxwM2ihafXaglcA5VTf6gpdgBCLRUugE2waT1I1k5recH3+y4A4I9CA==
  template:
    metadata:
      creationTimestamp: null
      name: rabbitmq-authentik-oauth
      namespace: rabbitmq
    type: Opaque
