apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config-template
  namespace: rabbitmq
data:
  rabbitmq.conf.template: |
    loopback_users.guest = false
    auth_backends.1 = rabbit_auth_backend_oauth2
    auth_backends.2 = rabbit_auth_backend_internal

    oauth_enabled = true
    oauth_client_id = ${OAUTH_CLIENT_ID}
    oauth_client_secret = ${OAUTH_CLIENT_SECRET}
    oauth_provider_url = https://authentik.homelab.rivetcode.com/application/o/rabbitmq/
    oauth_scope = openid profile email

    resource_server_id = ${OAUTH_CLIENT_ID}
    jwks_url = https://authentik.homelab.rivetcode.com/application/o/rabbitmq/jwks/
