---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rabbitmq-secret
  namespace: rabbitmq
spec:
  encryptedData:
    password: AgAd9DUeEO2QYf5iO1ZXeBY0+lfEWhTQt9FTommYUqpsqZx7j5Dw5YEb/wnkaYbiVFu1TWM40pi/yfpdCiibXBm66gnuym5Qnm2buT0+4T9q6L5p5IeCOUI5GIJMhkjN8ztfdJCEczrDI5nktbASg8SmrSxHgKFBo54scId4PNsI+BgK7/6gmCt7uJeAIBZzk/SoNiPjpfPukYxtkgvrAGX3DmtipCqp9oO0sKZh/gdAbNDWFLM+6RErgG5ytbthXIWCl0OyDZD7Xose4O+XDyQrIBv3zUTke1zE+Ihmau4DL6pSq56NWqHbeoe8e972ALPWIY0SVYEhZyQSgK5EDJ9VOOOo1pl8y03WNkm9LZbnrY+dHrPMWqOH3Pdn/fv3UAUekeGaf1Se9Il0LTcWBHAaWOLVhpc8vdYln7ldIwNQfM5OB94Cfg9O+bwwd/EnK5fdMbcSMUiYz6JS9Ig4+ii4sMocyENWBq9vZY5w1IbK+989Dd/6Xac7SqoDilKYPTAg6zBUfcjxLTVDkGjPMzuBQmvrub4FZb+U6A2RNW4gWMazCUOqHScuPY6u4qxzYEidXHYfqv0ZucK+PFM1FZDr+Cy6LMAtr+fTJlWqpHyEffBkm8OjRJAFBVJuZU2aRNu7KEhkpt0OVlkhHHDGWRAXhWrzQqsk3EkiYiOaCOLzsNTgsXunfxOspWJjwmcadkMlbmkDpeXK3g==
    username: AgDC4YE6/xsubu6wt7DdxkFRwk+xg26sBbw94RBsY+10qg7g5hh95pKcEiqPM+TJI5oE0pk4uPM1VoWXtmrX7OGqISUKuNp6AjbDzqSz20cDJ5/R3vf8qqI9xfxmF/SrQMgXhqU6snZ218dW5QYN3VY/+nF57rSy8Lm25DU6u58yv8l5bR72tGnE2E71AlhXrDbiLhZGIBCQY1XIJR3PZnQoNuRmTIpGmmtcCFN8046P3NW5vimWmVm4Lkqwkh2/Abws9hKj1b7orqtD/bfFhfqmST1R0RAEK9HunI0ZUMqibD6MeIRjIhmcmzlKfYHXRFqcwSjMW32cgLI83XgnnGowZgPjxjuxA1GlvtY5DYvyUmIiJQpIYiTIDOjMHXou9RDPpqQ/1su0mrIPFXTGpIyIPWshGKk4UTLz5P0tYBR9HQi8R2BSYgKzhVRPUVoq/6X2rPYdrHtaf+9VnAXcJzcfIRKfazA+o0juKlfNhftotfW3CDqD8NIphVzwMLDqhGcnJZbF3mOqjXspCLqRogonZ1xQmM7CH+L/h4t0AqUb5mFoYlrFlc5oQbck1Ep7Pu/bhVdLLTdwHqmH9x/EGclAoNdHf3hngaZvaAftHenOsX+8uEbGPbjHUmvWW9UphM/Fwr87Kemxfa4AH4sQJ7ALhfIXad6ehHDgkmtZDjX88OQwj1NAXzWM+67ikeimQ8oyDzJa+KJ6nA==
  template:
    metadata:
      name: rabbitmq-secret
      namespace: rabbitmq
    type: Opaque
