apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ollama
  namespace: ollama
spec:
  interval: 5m
  chart:
    spec:
      chart: ollama
      version: 9.18.0
      sourceRef:
        kind: HelmRepository
        name: ollama
        namespace: flux-system
      interval: 5m
  # https://github.com/trueforge-org/truecharts/blob/master/charts/stable/ollama/values.yaml
  values:
    image:
      repository: harbor.homelab.rivetcode.com/dockerhub-proxy/ollama/ollama
    resources:
      requests:
        memory: "8Gi"
      # explicitly set no limits
      limits:
        memory: null
        cpu: null
    service:
      main:
        targetSelector: main
    workload:
      ui:
        # use our separate open web-ui install
        enabled: false
    persistence:
      config:
        enabled: true
        size: 30Gi
        storageClass: "longhorn-ha-2"
      # not needed since open web-ui from this Helm chart is disabled
      data:
        enabled: false
