apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rabbitmq
  namespace: rabbitmq
spec:
  interval: 5m
  chart:
    spec:
      chart: rabbitmq
      # https://repo.broadcom.com/bitnami-files/index.yaml
      # https://artifacthub.io/packages/helm/bitnami/rabbitmq
      version: '16.0.8'
      sourceRef:
        kind: HelmRepository
        name: rabbitmq
        namespace: flux-system
      interval: 5m
  # https://github.com/bitnami/charts/blob/main/bitnami/rabbitmq/values.yaml
  values:
    service:
      type: LoadBalancer
    metrics:
      enabled: true
