apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rabbitmq
  namespace: rabbitmq
spec:
  interval: 5m
  # https://repo.broadcom.com/bitnami-files/index.yaml
  # https://artifacthub.io/packages/helm/bitnami/rabbitmq
  # https://github.com/fluxcd/flux2/issues/5089
  chartRef:
    kind: OCIRepository
    name: rabbitmq
    namespace: flux-system
  # https://github.com/bitnami/charts/blob/main/bitnami/rabbitmq/values.yaml
  values:
    service:
      type: ClusterIP
    metrics:
      enabled: true
