apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rabbitmq
  namespace: rabbitmq
spec:
  interval: 5m
  # https://repo.broadcom.com/bitnami-files/index.yaml
  # https://artifacthub.io/packages/helm/bitnami/rabbitmq
  # https://github.com/fluxcd/flux2/issues/5089
  chartRef:
    kind: OCIRepository
    name: rabbitmq
    namespace: flux-system
  # https://github.com/bitnami/charts/blob/main/bitnami/rabbitmq/values.yaml
  values:
    service:
      type: ClusterIP
    metrics:
      enabled: true
    extraPlugins: "rabbitmq_auth_backend_oauth2"
    extraEnvVars:
      - name: OAUTH_CLIENT_ID
        valueFrom:
          secretKeyRef:
            name: rabbitmq-authentik-oauth
            key: OAUTH_CLIENT_ID
      - name: OAUTH_CLIENT_SECRET
        valueFrom:
          secretKeyRef:
            name: rabbitmq-authentik-oauth
            key: OAUTH_CLIENT_SECRET
    podTemplate:
      initContainers:
        - name: config-template
          image: busybox
          command:
            - sh
            - -c
            - |
              echo "Generating rabbitmq.conf from template..."
              envsubst < /config-template/rabbitmq.conf.template > /config/rabbitmq.conf
              echo "Generated config:"
              cat /config/rabbitmq.conf
          volumeMounts:
            - name: config-template
              mountPath: /config-template
            - name: config
              mountPath: /config
      extraVolumes:
        - name: config-template
          configMap:
            name: rabbitmq-config-template
        - name: config
          emptyDir: {}
      extraVolumeMounts:
        - name: config
          mountPath: /opt/bitnami/rabbitmq/etc/
