apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: config-rabbitmq
  namespace: kube-system
spec:
  interval: 10m
  dependsOn:
  - name: rabbitmq
  path: ./configs/
  prune: true # remove any elements later removed from the above path
  timeout: 2m
  sourceRef:
    kind: GitRepository
    name: rabbitmq-configs
  retryInterval: 1m
