---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cilium-helmrelease.yaml
configMapGenerator:
  - name: cilium-helm-values
    files:
      - values.yaml=./cilium-helmvalues.yaml
configurations:
  - kustomizeconfig.yaml
