apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trivy
  namespace: trivy-system
spec:
  interval: 5m
  chart:
    spec:
      chart: trivy-operator
      # https://aquasecurity.github.io/helm-charts/index.yaml
      # https://aquasecurity.github.io/trivy-operator/latest/getting-started/installation/helm/
      version: '0.27.0'
      sourceRef:
        kind: HelmRepository
        name: trivy
        namespace: flux-system
      interval: 5m
  install:
    crds: CreateReplace
  # https://github.com/aquasecurity/trivy-operator/blob/main/deploy/helm/values.yaml
  values:
    serviceMonitor:
      enabled: true
    trivy:
      ignoreUnfixed: false
