---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: karakeep-litellm-api-key-secret
  namespace: karakeep
spec:
  encryptedData:
    OPENAI_API_KEY: AgCHVgocNm6w6+eNclixITCF/Wm/BmTf0ut6ktLP/kAxXvthWSfQQoTcWbSIESRThg83pfgWsL2Aq+flIt4le+AVAc7kFwh326+gfJu/sraPrGYEek0XR1eOS12S0osuatrclfvQyCwoJXu8HO+/vNSw4RdZbonaVkbdwDLGiAl5k7uKBAcxMR0ncXVAz2y842W8r1AazXNhxMEqNgdvSMDI+pV2Ki5onQ/AV0x/B6S2RISAsjYNSBnYN5nqz3lV95Pd4bAQ8VZ/LvHfsUuYrAPXyTpcyC3OGLqyFsc0o60SMyU2XJQwgu6QZWxMlfc8z1z4EhCUuur3750zReJd6s0zj0H0Mrx8181oczyG4X/mvSrvHcN098lzFrN7JyZscjwT2BWSBixiRRgfPWkgI3MW0SZQUy2lLqI7Uugn7sG/j5lb4GTzGXHgiCv9nheJV3WxFjzDx57FPgKlKgI2b9PIrwZ1MIfpepqEMUMHPwfuLH+aH9LY0UNWATWTxq6sPTbPBv1YhR41qu+aKBZk5A7V38QIAXRfIuKNDzDHV0OareFshzaVk6F/FHu18qezHRWnx3DIhskiRgrsCIy7SQZshkz7n6ykZ32NSrFz3XTAa/dgyhu/filVzOVZK1y2gbkrinwgOzplKRfIOuWbZWR/hzJQJBMEMadpN1MPBeaaFKxmu8SUiNSMhJ85l8i2b5qpgt+KZx1nVlQXqkrl7FRRh6AL8iijdBjj
  template:
    metadata:
      name: karakeep-litellm-api-key-secret
      namespace: karakeep
    type: Opaque
