apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: postgresql-ingressroute-tcp
  namespace: postgresql
  annotations:
    gethomepage.dev/href: "tcp://postgresql.homelab.rivetcode.com:5432"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: PostgreSQL
    gethomepage.dev/group: Kubernetes
    gethomepage.dev/icon: postgresql.png
    gethomepage.dev/app: postgresql # optional, may be needed if app.kubernetes.io/name != ingress metadata.name
    gethomepage.dev/name: Postgresql
spec:
  entryPoints:
    - postgres
  routes:
    - match: HostSNI(`*`)  # or use HostSNI(`postgresql.homelab.rivetcode.com`) if TLS is configured
      services:
        - name: postgresql
          port: 5432
