apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: postgresql-cert
  namespace: postgresql
spec:
  secretName: postgresql-certificate-secret
  dnsNames:
    - "postgresql.homelab.rivetcode.com"
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
