apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: spark-operator
  namespace: spark-operator
spec:
  interval: 5m
  chart:
    spec:
      chart: spark-kubernetes-operator
      # https://kubeflow.github.io/spark-operator/index.yaml
      # https://github.com/kubeflow/spark-operator
      version: '2.2.1'
      sourceRef:
        kind: HelmRepository
        name: spark-kubernetes-operator
        namespace: flux-system
      interval: 5m
  install:
    crds: CreateReplace
  # https://github.com/kubeflow/spark-operator/blob/master/charts/spark-operator-chart/values.yaml
  values:
    # optional values here
