apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: spark-kubernetes-operator
  namespace: flux-system
spec:
  interval: 5m
  url: https://apache.github.io/spark-kubernetes-operator
