apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: spark-kubernetes-operator
  namespace: flux-system
spec:
  interval: 5m
  # this is maintained by the Apache Spark community
  # https://github.com/apache/spark-kubernetes-operator
  #url: https://apache.github.io/spark-kubernetes-operator

  # this is maintained by Kubeflow, seems to be more popular
  # https://github.com/kubeflow/spark-operator
  url: https://kubeflow.github.io/spark-operator
