apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: podinfo-ingressroute
  namespace: podinfo
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`podinfo.homelab.rivetcode.com`)
    kind: Rule
    services:
    - name: podinfo
      port: 80
  tls:
    certResolver: cloudflare-clusterissuer
    domains:
      - main: "podinfo.homelab.rivetcode.com"
