apiVersion: batch/v1
kind: Job
metadata:
  name: create-authentik-podinfo-client
  namespace: authentik
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: create-client
          image: curlimages/curl:latest
          env:
            - name: AUTHENTIK_API_URL
              value: "http://authentik.homelab.rivetcode.com/api/v3"
            - name: AUTHENTIK_USERNAME
              valueFrom:
                secretKeyRef:
                  name: authentik-admin-credentials
                  key: AUTHENTIK_BOOTSTRAP_EMAIL
            - name: AUTHENTIK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: authentik-admin-credentials
                  key: AUTHENTIK_BOOTSTRAP_PASSWORD
          command:
            - /bin/sh
            - -c
            - |
              echo "Waiting for Authentik API to be ready..."
              until curl -s -f ${AUTHENTIK_API_URL}/health/; do
                echo "Authenti–∫ API not ready, retrying in 5 seconds..."
                sleep 5
              done
              echo "Authentik API is ready, proceeding..."

              # Get API token
              TOKEN=$(curl -s -X POST "${AUTHENTIK_API_URL}/auth/token/" \
                -H "Content-Type: application/json" \
                -d "{\"username\": \"${AUTHENTIK_USERNAME}\", \"password\": \"${AUTHENTIK_PASSWORD}\"}" | jq -r '.access')

              if [ -z "$TOKEN" ] || [ "$TOKEN" = "null" ]; then
                echo "Failed to get API token"
                exit 1
              fi
              echo "Creating OIDC client in Authentik..."
              curl -X POST "${AUTHENTIK_API_URL}/outpost/oidc/client/" \
                -H "Authorization: Bearer $TOKEN" \
                -H "Content-Type: application/json" \
                -d '{
                  "name": "podinfo",
                  "redirect_uris": ["https://podinfo.homelab.rivetcode.com/oauth/callback"],
                  "client_type": "confidential",
                  "response_types": ["code"],
                  "scope": "openid profile email",
                  "require_consent": false
                }'

              echo "Job completed."
