apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: podinfo-ingressroute
  namespace: podinfo
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-clusterissuer # the ClusterIssuer
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`podinfo.homelab.rivetcode.com`)
    kind: Rule
    services:
    - name: podinfo
      port: 80
  tls:
    secretName: podinfo-certificate-secret
