apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-configmap
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        # forward all non homelab.local queries to Pi-Hole
        forward . 192.168.1.226
        cache
        log
    }

    homelab.local:53 {
        file /etc/coredns/zones/homelab.local.zone
    }

    *.homelab.local:53 {
        file /etc/coredns/zones/homelab.local.zone
    }
