apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitea
  namespace: gitea
spec:
  interval: 5m
  chart:
    spec:
      chart: gitea
      # note this doesn't match the gitea version, the helm chart has it's own versioning
      # https://dl.gitea.com/charts/index.yaml
      version: '12.4.0'
      sourceRef:
        kind: HelmRepository
        name: gitea
        namespace: flux-system
      interval: 5m
  # https://gitea.com/gitea/helm-gitea/src/branch/main/values.yaml
  values:
    gitea:
      metrics:
        enabled: true
    service:
      http:
        type: ClusterIP
    # the following for postgresql and valkey are just a temporary stop-gap until long-term replacements can be
    # found given the Bitnami shutdown and move to commercial offerings
    # https://gitea.com/gitea/helm-gitea/issues/903
    postgresql-ha:
      postgresql:
        image:
          repository: bitnamilegacy/postgresql-repmgr
          tag: 17.6.0-debian-12-r2
      pgpool:
        image:
          repository: bitnamilegacy/pgpool
          tag: 4.6.3-debian-12-r0
    valkey-cluster:
      image:
        repository: bitnamilegacy/valkey-cluster
        tag: 8.1.3-debian-12-r3
