apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gitea-config
  namespace: gitea
spec:
  interval: 10m
  path: ./configs/
  prune: true
  dependsOn:
    - name: gitea
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
