apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitea
  namespace: gitea
spec:
  interval: 5m
  chart:
    spec:
      chart: gitea
      # note this doesn't match the gitea version, the helm chart has it's own versioning
      # https://dl.gitea.com/charts/index.yaml
      version: '11.0.0'
      sourceRef:
        kind: HelmRepository
        name: gitea
        namespace: flux-system
      interval: 5m
  # https://gitea.com/gitea/helm-gitea/src/branch/main/values.yaml
  values:
    service:
      http:
        type: LoadBalancer
        clusterIP:
