apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: frigate
  namespace: frigate
spec:
  interval: 5m
  chart:
    spec:
      chart: frigate
      # https://github.com/blakeblackshear/blakeshome-charts/tree/master/charts/frigate
      version: '7.8.0'
      sourceRef:
        kind: HelmRepository
        name: frigate
        namespace: flux-system
      interval: 5m
  # https://github.com/blakeblackshear/blakeshome-charts/blob/master/charts/frigate/values.yaml
  values:
    persistence:
      config:
        # Enables persistence for the config directory
        enabled: true
        storageClass: "longhorn"
    extraEnv:
      - name: FRIGATE_RTSP_PASSWORD
        valueFrom:
          secretKeyRef:
            name: frigate-rtsp-secret
            key: FRIGATE_RTSP_PASSWORD
    # frigate configuration - see [Docs](https://docs.frigate.video/configuration/index) for more info
    config: |
      mqtt:
        # Required: host name
        host: rabbitmq.homelab.rivetcode.com
        # Optional: port (default: shown below)
        port: 1883
        # Optional: topic prefix (default: shown below)
        # WARNING: must be unique if you are running multiple instances
        topic_prefix: frigate
        # Optional: client id (default: shown below)
        # WARNING: must be unique if you are running multiple instances
        client_id: frigate
        # Optional: user
        user: rabbitmq
        # Optional: password
        # NOTE: Environment variables that begin with 'FRIGATE_' may be referenced in {}.
        #       eg. password: '{FRIGATE_MQTT_PASSWORD}'
        password: rabbitmq
        # Optional: interval in seconds for publishing stats (default: shown below)
        stats_interval: 60

      detectors:
        cpu1:
          type: cpu

      cameras:
        inside:
          ffmpeg:
            inputs:
              # sub-stream, lower quality and FPS
              # - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.1.111:554/cam/realmonitor?channel=1&subtype=1
              #   roles:
              #     - detect
              # full 4k stream
              - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.1.111:554/cam/realmonitor?channel=1&subtype=0
                roles:
                  - record
