apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: frigate
  namespace: frigate
spec:
  interval: 5m
  chart:
    spec:
      chart: frigate
      # https://github.com/blakeblackshear/blakeshome-charts/tree/master/charts/frigate
      version: '7.8.0'
      sourceRef:
        kind: HelmRepository
        name: frigate
        namespace: flux-system
      interval: 5m
  # https://github.com/blakeblackshear/blakeshome-charts/blob/master/charts/frigate/values.yaml
  values:
    persistence:
      config:
        # Enables persistence for the config directory
        enabled: true
