apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
  namespace: alloy
spec:
  interval: 5m
  chart:
    spec:
      chart: alloy
      version: '1.8.1'
      sourceRef:
        kind: HelmRepository
        name: alloy
        namespace: flux-system
      interval: 5m
  # https://github.com/grafana/alloy/blob/main/operations/helm/charts/alloy/values.yaml
  values:
    alloy:
      configMap:
        create: true
        content: |
          logging {
            level = "info"
          }

          discovery.kubernetes "pods" {
            role = "pod"
          }

          loki.source.kubernetes "pods" {
            targets = discovery.kubernetes.pods.targets

            forward_to = [loki.process.filter.receiver]
          }

          loki.process "filter" {

            # Drop kube-system completely
            stage.match {
              selector = "{namespace=\"kube-system\"}"
              action   = "drop"
            }

            # Drop noisy pause/coredns containers
            stage.match {
              selector = "{container=~\"pause|POD|coredns\"}"
              action   = "drop"
            }

            # Drop health checks
            stage.regex {
              expression     = ".*(GET /health|/ready|/live).*"
              source         = "line"
              action         = "drop"
            }

            forward_to = [loki.write.default.receiver]
          }

          loki.write "default" {
            endpoint {
              url = "http://loki-gateway.loki.svc.cluster.local/loki/api/v1/push"
            }
          }
