apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gatus-config
  namespace: gatus
spec:
  interval: 10m
  path: ./configs/
  prune: true
  dependsOn:
    - name: gatus
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
