apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gatus
  namespace: gatus
spec:
  interval: 5m
  chart:
    spec:
      chart: gatus
      # https://twin.github.io/helm-charts/index.yaml
      version: '1.4.2'
      sourceRef:
        kind: HelmRepository
        name: gatus
        namespace: flux-system
      interval: 5m
  # https://github.com/TwiN/helm-charts/blob/master/charts/gatus/values.yaml
  values:
    service:
      type: ClusterIP
    persistence:
      enabled: false
    # Gatus configuration
    # https://github.com/TwiN/gatus#configuration
    config:
      endpoints:
        - name: podinfo
          url: https://podinfo.homelab.rivetcode.com
          interval: 60s
          conditions:
            - "[STATUS] == 200"
        - name: authentik
          url: https://authentik.homelab.rivetcode.com
          interval: 60s
          conditions:
            - "[STATUS] == 200"
        - name: longhorn
          url: https://longhorn.homelab.rivetcode.com
          interval: 60s
          conditions:
            - "[STATUS] == 200"
        - name: gitea
          url: https://gitea.homelab.rivetcode.com
          interval: 60s
          conditions:
            - "[STATUS] == 200"
        - name: headlamp
          url: https://headlamp.homelab.rivetcode.com
          interval: 60s
          conditions:
            - "[STATUS] == 200"
        - name: kubernetes-dashboard
          url: https://kubernetes-dashboard.homelab.rivetcode.com
          interval: 60s
          conditions:
            - "[STATUS] == 200"
        - name: defectdojo
          url: https://defectdojo.homelab.rivetcode.com
          interval: 60s
          conditions:
            - "[STATUS] == 200"
        - name: rabbitmq
          url: https://rabbitmq.homelab.rivetcode.com
          interval: 60s
          conditions:
            - "[STATUS] == 200"
        - name: prometheus
          url: https://prometheus.homelab.rivetcode.com
          interval: 60s
          conditions:
            - "[STATUS] == 200"
        - name: traefik
          url: https://traefik.homelab.rivetcode.com
          interval: 60s
          conditions:
            - "[STATUS] == 200"
        - name: stirlingpdf
          url: https://stirlingpdf.homelab.rivetcode.com
          interval: 60s
          conditions:
            - "[STATUS] == 200"
        - name: recipes
          url: https://recipes.homelab.rivetcode.com
          interval: 60s
          conditions:
            - "[STATUS] == 200"
        - name: boardgames
          url: https://boardgames.homelab.rivetcode.com
          interval: 60s
          conditions:
            - "[STATUS] == 200"
        - name: datascience
          url: https://datascience.homelab.rivetcode.com
          interval: 60s
          conditions:
            - "[STATUS] == 200"
        - name: volcano
          url: https://volcano.homelab.rivetcode.com
          interval: 60s
          conditions:
            - "[STATUS] == 200"
