apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gatus
  namespace: gatus
spec:
  interval: 5m
  chart:
    spec:
      chart: gatus
      # https://twin.github.io/helm-charts/index.yaml
      version: '1.2.0'
      sourceRef:
        kind: HelmRepository
        name: gatus
        namespace: flux-system
      interval: 5m
  # https://github.com/TwiN/helm-charts/blob/master/charts/gatus/values.yaml
  values:
    service:
      type: LoadBalancer
    persistence:
      enabled: false
    # Gatus configuration
    # https://github.com/TwiN/gatus#configuration
    config:
      endpoints:
        - name: podinfo
          url: https://podinfo.homelab.rivetcode.com
          interval: 60s
          conditions:
            - "[STATUS] == 200"
        - name: authentik
          url: https://authentik.homelab.rivetcode.com
          interval: 60s
          conditions:
            - "[STATUS] == 200"
        - name: longhorn
          url: https://longhorn.homelab.rivetcode.com
          interval: 60s
          conditions:
            - "[STATUS] == 200"
        - name: gitea
          url: https://gitea.homelab.rivetcode.com
          interval: 60s
          conditions:
            - "[STATUS] == 200"
        - name: headlamp
          url: https://headlamp.homelab.rivetcode.com
          interval: 60s
          conditions:
            - "[STATUS] == 200"
        - name: kubernetes-dashboard
          url: https://kubernetes-dashboard.homelab.rivetcode.com
          interval: 60s
          conditions:
            - "[STATUS] == 200"
