apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: homepage-config
  namespace: homepage
spec:
  interval: 10m
  path: ./configs/
  prune: true
  dependsOn:
    - name: homepage
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
