apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
    ingress: true # default, enable ingress
    traefik: true # enable traefik ingressRoute
    gateway: true # enable gateway-api
  settings.yaml: ""
  #settings.yaml: |
  #  providers:
  #    longhorn:
  #      url: https://longhorn.my.network
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: ""
  services.yaml: |
    - Kubernetes:
        - Heimdall:
            href: https://portal.homelab.rivetcode.com
            description: Heimdall
            icon: heimdall.png
        - Traefik:
            href: https://traefik.homelab.rivetcode.com
            description: Traefik
            icon: traefik.png
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
  docker.yaml: ""
