apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: steam-analysis
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/carlsonp/steam-analysis
  ref:
    branch: master
