apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: postgresql
  namespace: flux-system
spec:
  interval: 5m
  url: oci://registry-1.docker.io/bitnamicharts/postgresql
  ref:
    semver: ">=16.7.13"
