apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 5m
  chart:
    spec:
      chart: longhorn
      version: '1.6.2'
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
      interval: 1m
  values:
    # see stock version
    # https://github.com/longhorn/longhorn/blob/master/chart/values.yaml
    service:
      ui:
        type: LoadBalancer
