apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 5m
  chart:
    spec:
      chart: longhorn
      version: '1.9.2'
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
      interval: 5m
  values:
    # see stock version
    # https://github.com/longhorn/longhorn/blob/master/chart/values.yaml
    metrics:
      ServiceMonitor:
        enabled: true
    service:
      ui:
        type: ClusterIP
    defaultSettings:
      createDefaultDiskLabeledNodes: false
    persistence:
      defaultClass: true
      defaultFsType: ext4
