apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn-config
  namespace: longhorn-system
spec:
  interval: 10m
  path: ./configs/
  prune: true
  dependsOn:
    - name: longhorn
  wait: true # wait until longhorn is fully deployed
  sourceRef:
    kind: GitRepository
    name: flux-system
