apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  interval: 5m
  chart:
    spec:
      chart: home-assistant
      # https://github.com/pajikos/home-assistant-helm-chart
      version: '0.3.38'
      sourceRef:
        kind: HelmRepository
        name: home-assistant
        namespace: flux-system
      interval: 5m
  # https://github.com/pajikos/home-assistant-helm-chart/blob/main/charts/home-assistant/values.yaml
  values:
    controller:
      type: StatefulSet
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 5Gi
      storageClass: longhorn
    ingress:
      enabled: false   # Traditional ingress
      external: true # External ingress
    # TODO: enable the service monitor at some point via Prometheus
    # serviceMonitor:
    #   enabled: true
    configuration:
      # Enable or disable the configuration setup for Home Assistant
      enabled: true
      # Force init will merge the current configuration file with the default configuration on every start
      # This is useful when you want to ensure that the configuration file is always up to date
      forceInit: true
      # List of trusted proxies in the format of CIDR notation in a case of using a reverse proxy
      # Here is the list of the most common private IP ranges, use your list of possible trusted proxies, usually, it's the IP of the reverse proxy
      trusted_proxies:
        - 10.0.0.0/8 # Add the IP address of your cluster CIDR
