apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  interval: 5m
  chart:
    spec:
      chart: home-assistant
      # https://github.com/pajikos/home-assistant-helm-chart
      version: '0.3.30'
      sourceRef:
        kind: HelmRepository
        name: home-assistant
        namespace: flux-system
      interval: 5m
  # https://github.com/pajikos/home-assistant-helm-chart/blob/main/charts/home-assistant/values.yaml
  values:
    controller:
      type: StatefulSet
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 5Gi
      storageClass: longhorn
    ingress:
      enabled: false   # Traditional ingress
      external: true # External ingress
