apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: home-assistant-config
  namespace: home-assistant
spec:
  interval: 5m
  path: ./clusters/home/apps/home-assistant/home-assistant/configs/
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
