apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik-config
  namespace: kube-system
spec:
  interval: 5m
  path: ./clusters/home/apps/kube-system/traefik/configs/traefik/
  prune: true # remove any elements later removed from the above path
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
