apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  interval: 5m
  chart:
    spec:
      chart: keycloak
      # https://artifacthub.io/packages/helm/bitnami/keycloak
      version: '24.4.13'
      sourceRef:
        kind: HelmRepository
        name: keycloak
        namespace: flux-system
      interval: 5m
  # https://artifacthub.io/packages/helm/bitnami/keycloak
  values:
    service:
      type: LoadBalancer
