---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBKc9pCx2jj38SQ45FyZGaByfnpuADP/A3ehYfVpu2Lfxlay6MyKZ1YS8FofteWLGipioNGgkZ8DKLb681h/idYv2BEtRQrr/o1mmXU21v+iB40W7znU+eTP3cgWByDMYiYKk+GrQzVmirLVSX9pSTLx7oLMwZizug77HB/qMmBO4Cjz4pVrfEEnGgBwIcYmffLyRyOEX5XTjLASnIMIReHBWlPNFAPyEG1vC0BCEsq5HLVBtryJrvvmX5QHUTtXIFC/AuuRGvM2wTuFdpL222bPiDyPgpIPBlRb9VtvQ/TuG+cdCoWJnoS3Z7zHkuDuMIbeBogkZxs13y1hnPST8S2MLW9R8kgylP1RxgvCupeeGjm0svtq7YQcUIKELhunYZ1wKEVlMa7UdXqQLlPE1AuD4qHd9eVxycJCiZbesauMdHpj/lhKtSk5dqJnnqx64P6eiWh5WLuN0FHu5nlHpnkkJV7vRP/fOObrzkgkrE9FnU3QXHS26Ybsm7pBBCF3JGByQvRFeDot/cnHguqKJTDxp/5kW5nSsD0m3P9e3LO5SFv5g+BpdMBPNsh24FsO/8LDoqGSnrcQIveDk3/9llupTuNkGBidjtCsmIIyrYDd+8TFp4o0gLRL3S1AdQKYt4+xTfsqoq5rNlD0SKfwPo8DfuG+WXCtLFTVfctZYr6ufc2R3MATbtMTQU+TtSxKsbYY1R9i8HjeRxIX0cufwdH5h6o2pqZhoONjiDKwO6t56ddCLxhCHpn
    email: AgCIsHJmageI9hnhvVn5cMhIyt9XC3KrMoXN8i3LjqHAvC1CQaEQYUOiYUNY7XDGmCNQ9/HE90BDi5uJ5oelZPHlWOeJtXmDZI/WdwMu5ApRX+XtEw+qwO1QQ1dysfnTMxJw/RefoFW61PHu9vLDJMlgVT+6G6WDrqaCdJtFCNxyhiTh+d2CjzSMsqXSsmWrXpkH28laSYMFEttdrI1d+fw2ZINS8W4SW7+F8difKGhyayEAd9J5qoKUrQFPh3Q3/zSZuu9edP8jA8QbxoBWZS+s4a1QIW3mOpWdOPyyCtVBYhQBh5iRWUdojDx4OwnO/wg7dMVSpyqFR+9gQhZOtc1PJbpOGK8D3r2zq2eBlSFyBewuk6r/8QvWQ0s01DESlqqxoCZ480JqWb2C8vx83ifIC4xrIfg+4ttujwRPu9IS5rIy6jY3gj7zJGporkkxcwoStLou96j61v30+gJEdRm+H3vV1lpp+zU4Ikt9xEWStcVX/KMUn5KAqZj4Z3NolzKAYJxMzILaiPak/l8QpXfvlNMhmoAJUD+RA5ssUspuxsnufCuXABvZ0FFp2MT9FzKQekgoXSmIe2MYzIxDHN2yF2/G/yG434uT7hafsVzOqk5BZMlwVTdR9tU1mSnNMRtMwCeJPxDj0I7JjypvByeMSNqDCzbteCugXOzTGxfxBe+rQvWPxdbdyQIjfffANTuXbMxe1LChpte98+3WX7zPodET9yQ=
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
