---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgA1nfX931Z8pnFSQfw7ngFXo1O+lLkrnjCg6LKsI10oVVAmRu+NaQXl4tQB1K37wRriiHmMcE9yldq4K6JTXPYf6lE/I/Tjl2eDUTPxS0RmDgBB2O3PU+olSF1qDLO9IcSHoXr69oxlcHXcdOh2U0XmxeCaSlsrzWwJloafPi7Xf7GQLmCWBK1uS0oFj9uOKx8SU6k+Jiicc+tGNA0dIFY6WXpS4N8HHgJYhafLcIuyeN79bgkymv5E7DBRBQmWtK23aVohiThhMXhslgmgUy2BXO1XRM0WKbGlLxD2e6MbeoQ88G0Xh8MaM19rijIeSgPYzNzNPpC+ZD9n2PWivmzAwUqJe/o46gMaciszKLXBxRl8wWwG+IR4svR3b0Z1W536m4+w7+nf19HGjPrgmKsOYCij8n99lMWBnrCMvvw5wIexx85EZT8ZHSUZN9td3alyjzxvkIMUBOGTT/Q9hAqM4Ede7AGHHe6K7v5i5J1ECtwp5SBLgIhFx+epOMCIUjul3axHpS0zbirIbmylTad4XnpMaJvMjr/vh38TnA8xAmtc/Z4l2qA9PfX1FvMfyLkq+M8cUPqUNrQwg0an78CQa/DnkIj36uubQ0ipZ+9WkqYM/h2OiG/zJGVZEWH8C0r0G20uIinkVUjg7DvkJTtnd5d0VYcYHRjjFYmR3/6gE9ETkDR894lbXUKvA9yr0Z+pNv5itjo9QlMX3oYTLJqzf0VKwWWoUuhIbnSGzMYcDs+onDKVUw9QDkyzmOgGLjN1r3cXVA==
    email: AgA2mkD8/Rn6GQhM21WheQHTf/QPl8Qkhkt6Lwb2O+lcrZ9d87NOrqGdL169d/sbvaYCEccVyHybXx8GAlhRM4xzfN5da8bqKxHic6q93MvqcyAseRgCTQBJ7Bd1Vtk4kwe4V50l3MwYmKhtcEf8QefgVMNOdlikDpjxr5N1ShT8QpzDcT6ZYoKcq9MqtmFA21doNFeFsgH6ncNqC1Q1z/XXMVWZC/mFRMRA4G0sisRn4RsNXzgLyPlP3PQZspfwnl25ZJYQ6CH5Z85EFwLb9H9k8jUrtqaf9nvOE0wyrf2a3CJ3s92y1vJBPo2RTDwB17eR7LiP8IJqoMP6VVSlLOR/BqczxghrGcRQspupoGKskjhxStina9oEBi0vI+Ivr2U1HcDKkZDaGJWbtU/tj6DSWU3YDL5MZ71LKHRZw8KBK9NNqxk0ft75RQ4jow6Kh4Csl/zj104Ew+NK8Uk00CATduwn/GRT6NQ1JKviUOvzi7s8pS5MGuRb3mWpXBwbHW59Je8omoFDeQajV1LZcpDfdGVC83Mtmai9OF1MMR3Sbk05stj9IY2RkDwG9wZKoBjzrnkcu2cMtqsbD4BJFGPC1UlEdmf5Z8SDmBv0y04Rx5nwK+MDehXuWaVO4DJaEL1rXSX6l7lr9TamtgT9PaKs9PdQh0YdoCD6AuI+upIYgV2S+C6SpWYbRJ0wQpxfmspPmqx6448v64ut87bxNTCbqE1zFkc=
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
