apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: defectdojo
  namespace: flux-system
spec:
  interval: 5m
  url: https://raw.githubusercontent.com/DefectDojo/django-DefectDojo/helm-charts
