apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: config-recipes
  namespace: kube-system
spec:
  interval: 5m
  dependsOn:
  - name: my-recipes-cooklang
  path: ./configs/
  prune: true # remove any elements later removed from the above path
  timeout: 2m
  sourceRef:
    kind: GitRepository
    name: recipes-configs
  retryInterval: 1m
