apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jupyterlab-r-docker-stack-helm
  namespace: datascience
spec:
  interval: 5m
  chart:
    spec:
      chart: ./chart  # relative path in the repo
      sourceRef:
        kind: GitRepository
        name: jupyterlab-r-docker-stack-helm
        namespace: flux-system
  values:
    # optional custom values here
