apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jupyterhub
  namespace: datascience
spec:
  interval: 5m
  chart:
    spec:
      # https://hub.jupyter.org/helm-chart/index.yaml
      chart: jupyterhub
      version: '4.0.0'
      sourceRef:
        kind: HelmRepository
        name: jupyterhub
        namespace: flux-system
      interval: 5m
  # https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/HEAD/jupyterhub/values.yaml
  values:
    singleuser:
      image:
        name: "ghcr.io/firefly2442/jupyterlab-r-docker-stack-helm"
        tag: "latest"
        pullPolicy: "Always"
