apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: config-datascience
  namespace: kube-system
spec:
  interval: 1m
  dependsOn:
  - name: jupyterlab-r-docker-stack-helm
  path: ./configs/
  prune: true # remove any elements later removed from the above path
  timeout: 2m
  sourceRef:
    kind: GitRepository
    name: datascience-configs
  retryInterval: 1m
