apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: config-cert-manager
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
  - name: cert-manager
    namespace: flux-system
  namespace: cert-manager
  path: ./clusters/home/apps/cert-manager/cert-manager/configs/
  prune: true # remove any elements later removed from the above path
  timeout: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  retryInterval: 1m
