apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: config-cert-manager
  namespace: kube-system
spec:
  interval: 10m
  dependsOn:
  - name: cert-manager
  path: ./configs/
  prune: true # remove any elements later removed from the above path
  timeout: 2m
  sourceRef:
    kind: GitRepository
    name: cert-manager-configs
  retryInterval: 1m
