apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana-config
  namespace: grafana
spec:
  interval: 10m
  path: ./configs/
  prune: true
  dependsOn:
    - name: grafana
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
