apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: grafana
spec:
  interval: 5m
  chart:
    spec:
      chart: grafana
      # https://grafana.github.io/helm-charts/index.yaml
      # https://artifacthub.io/packages/helm/grafana/grafana
      version: '8.10.4'
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 5m
  # https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml
