apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-pool
  namespace: metallb-system
spec:
  addresses:
  # OpenWRT starts handing out DHCP addresses at 192.168.1.100
  - 192.168.1.10-192.168.1.99
  autoAssign: true
  avoidBuggyIPs: false
