apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: gatus-ingressroute
  namespace: gatus
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-clusterissuer
    gethomepage.dev/href: "https://gatus.homelab.rivetcode.com"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Gatus
    gethomepage.dev/group: Kubernetes
    gethomepage.dev/icon: gatus.png
    gethomepage.dev/app: gatus # optional, may be needed if app.kubernetes.io/name != ingress metadata.name
    gethomepage.dev/name: Gatus
    gethomepage.dev/widget.type: "gatus"
    # use .local domain name so we don't get blocked by authentik
    gethomepage.dev/widget.url: "http://gatus.gatus.svc.cluster.local"
    gethomepage.dev/pod-selector: ""
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`gatus.homelab.rivetcode.com`)
    kind: Rule
    services:
    - name: gatus
      port: 80
    middlewares:
      - name: authentik-service-middleware
        namespace: authentik
  tls:
    secretName: gatus-certificate-secret
