apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gatus-cert
  namespace: gatus
spec:
  secretName: gatus-certificate-secret
  dnsNames:
    - "gatus.homelab.rivetcode.com"
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
