apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn-ingressroute
  namespace: longhorn
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-clusterissuer
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`longhorn.homelab.rivetcode.com`)
    kind: Rule
    services:
    - name: longhorn
      port: 80
  tls:
    secretName: longhorn-certificate-secret
