---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitea-authentik-oauth
  namespace: gitea
spec:
  encryptedData:
    key: AgA1DLmeEdWT5JWQ4SpXPAM0XzQvfNTCETP4JiLzzxG7vrGEyhTSxIqpxgv0VDaUcRUCJJDLctCCcalUN6vKim+TeOo3sssHFci2jYPvKvuL4+g88AW6gLrhPQPK+d4T1ehNwlxUpf9jaP5WbG6Gt8GjgFzyiSuwhDfGSrGcnYGtMlJfyqqBr8gHkTc9X4tOL6nvwDhT0aJQ9h1gpE/uaD6rZuzp6aEYDt+x/hlO0wADJ2fymYD0RtNwkB5fcPdDZ06ueaybQRLhXKKKNnpSr5L+cdw6fllS3lbocIQWC/QlQasAHBiYbkWMN/yNbIdcERBb3dSjvjXEixP3z3PJBkCVdOqhfJAu7UaePZNYw/8EuDTFEJN8IZwOiVqEKxvoEmHT0/qefBPohu6BmsOwspXMR508p1QopIkOb94Skj1NuvETpnKugkRcRCBWAQcRiYF9r/Cm93jnPsc28hhxWsqXR9ZO7l4iW55fl6pKgISt1c4YDo4BUUC8l1qco8mwfM/1Djy0yfnAJGY9uRYCVinux7cLW0VEtYwwi66wgItQc25jCYvJ245Z3n24Lm/ttG7FMKb9QFHy1rftSj0wwx/4w7urxzXA7IhtHZcqOcd9CPQV6vrTQiSlVLl5HT9k3gwiov4Uryzyopsqcnh+VRlpPcppyuOl9C5kUs6MJTzRrramz6upeKHS7fpT35yPqvLT8VDNLljXZvfShI1zQ9yhkTrvnwtP3A59SDdSo5wosv+Hn6oOyvDZ
    secret: AgAn+d43rQI49XXU+X6+0yxR3Vc3lavGmHHcjF3mETEg/6BN6ruY2/YxBrx2v/MhRo/XXgUiOYnw1ldcMAc78/cRPLwgMw5isSEYzeAcU79CfwT5fsreGra/HmcqnE/l+sxvTzzcjSWPPBzAPf+XfTGJEslfjfBXjzvfIM0QyDMc6bWH+zGMa18vd0bh+7QCwTaP5U5nTTFbjWP/dpAmIRZzEj2KZxywoiyInC58RE0pJhuEOv59+juRGypDUeShBQfRE26MTgN+qCl4UF4IJeLv16l4AIL/ByYAI8xz/EUJgfEVzkWJ4SuWsEEc3Nb2KHcFzz9UIr+FQQ4zBMQ/kumbHPBu8H0pI9Bww1V3EmW0sTZ+yjrG6b1NFZ023DcEVwmobN2p+3pp9GGUmePOwoQJ6MF9P+qGQ26UN42KZN5AP3IvAyxuDOhwCbpR6CPHnaPt/h0kQxh5MAtu/cr8hbGF0EHqBZhcFokWVU8r/nGJQToljS29O4V10qEmbGNMjJqg/WLffjExU9nragfq5IwoNyuEcY95GdWPjIQ6XWwe4aYArR5s5nvuW+vBbSeNsVi4FTdmOGFbVNEd9yK1XsJsz3pfLYucg8XWwhDFlMEgbEtyO0+7XUUjKYw9aAR9vhSbs6p+QI8OihRVuW/KP2a9uEvSOxlN8zjG3e18yISA/P4r1JvWBnaGE1hPBgUgcrR6EWjB+Yy6mK5CM74NDGAtLXyVXuB0QVPaq3r9YgXPGe/6cOyFVaB3xGqHyi3DPKcq74t7/xRK+q16QYqQK3e965gfdxpUwvxvEzqaAOF+nWFn4yHV/FWMWE/iIgaUJsqwqBoaIzeag+idSXfwWMa0sccyrerMsPymhucU5GrCsA==
  template:
    metadata:
      name: gitea-authentik-oauth
      namespace: gitea
    type: Opaque
