apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: gitea-ingressroute
  namespace: gitea
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-clusterissuer
    gethomepage.dev/href: "https://gitea.homelab.rivetcode.com"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Gitea
    gethomepage.dev/group: Kubernetes
    gethomepage.dev/icon: gitea.png
    gethomepage.dev/app: gitea # optional, may be needed if app.kubernetes.io/name != ingress metadata.name
    gethomepage.dev/name: Gitea
    gethomepage.dev/widget.type: "gitea"
    # use .local domain name so we don't get blocked by authentik
    gethomepage.dev/widget.url: "http://gitea-http.gitea.svc.cluster.local:3000"
    gethomepage.dev/pod-selector: ""
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`gitea.homelab.rivetcode.com`)
    kind: Rule
    services:
    - name: gitea-http
      port: 3000
  tls:
    secretName: gitea-certificate-secret
