apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: gitea-ingressroute
  namespace: gitea
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-clusterissuer
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`gitea.homelab.rivetcode.com`)
    kind: Rule
    services:
    - name: gitea-http
      port: 3000
  tls:
    secretName: gitea-certificate-secret
