apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: convertx-cert
  namespace: convertx
spec:
  secretName: convertx-certificate-secret
  dnsNames:
    - "convertx.homelab.rivetcode.com"
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
