---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: litellm-cerebras-api-key-secret
  namespace: litellm
spec:
  encryptedData:
    CEREBRAS_API_KEY: AgA6lQ/XyPwF2E7lfUOCOl0pbOXyOI4ZFRt1DqwuRz4AVetLPQXITaqyQkOXfowoOjNZbcENvQJcueRTXzjdgqPP/erfo2YIbwqFNph3rumLPVDepo+dORBnF1twCyK4PPjxRQBUdYafiopLEgEi3rX6CRu9jioLNQCVSZfBt6yjC6X/4OGYf0dJF0j4z/etnH9pmJhNWcTKszqLO5lvBq9Hgk/ocjsgNM4q63p3W59C4B/csKXTi9p9n/q9Be/aPftnZX9URw+qG2QF7D05+3WKXsgOdbm43SMR6WN8YZSdBeLObbg8aoTu3pv+E09Ith9swAIEQO1tdyqSkYuuQVl1EBaolvTNfr3FO/D2m92FafAKmrtegC1yn9Q103l/0/ZkDvSbF5JFnU3+qttmDYx1q+pXlAyLWtdE2373Iw6H/GghtcY9ZdsCz/GA5olvlaJQ4ej8LvN5lwi6k0I1dozEPQWWyMUHvOa3/HaLF3kCCMcyF76xNQdMTj3n14+9kn1K7bHCUow9gcbXt56jYz0yp2Yvvjch+DQUD2n3aUK0/hUNQ/poErzagbKplm+G2pnG+VwgzEXzCcg8DDM5HmGZWughVfdMl33GZzcQpvhbvRFkn10gE96ORiqC7xZXvawWCoOAPU1Q1aucKQlV3JWmK7MelsZ8lGkLabJKTryr+0xGTaFNL2gXeOgRBGVV/PS2drqlomLskBrsnOLXDsxB0r7IKVrL/3yrrqouh4hnC/d52fKyHelui9aIi5cliasSgM1e
  template:
    metadata:
      name: litellm-cerebras-api-key-secret
      namespace: litellm
    type: Opaque
