---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: litellm-gemini-api-key-secret
  namespace: litellm
spec:
  encryptedData:
    GEMINI_API_KEY: AgCPGX75kwPJb7bOXYdBWmnhIw3TtZYa15775V5hvHGp4jsTgE6/yDeGAeaWh5yTAJgRIff5Icrg7zuUvpbnCb8gRGmhloF+AbHEKaO2YCsYwTbbOB9jz+wLl5R57ObUgkeDxoHJKQgnMwRYs5qO2XEAfj4inCPiFU9+HJWktsmJflQsQ0VkuxQsJJpGdq2A3en82O6IcP0uc0QUYYKR23CG0wC6QZ4eykg90DW77uhdZdC7Iq4azNX6mMlfoRsRlv+OqWQkeTu59aR/4OcPlmCTtuEGUUidtyIjCgxMdPBHwWKfuIQLxMMr5GDRKqP5Fc4HrH9tjH9LqUudQZ0sabGqLM8H7N4Zmlyfnp2VlmDv3YFubiamfCVlBNmfD7y9hS3u3Ic5fKMNUPu8QcqSHQ4aOslJMIsu3filwEZXSgMaVSwSL2EPECb15lXTsT9SV6GQutvFZhRA2bGkTNWqscZ5XhaVwFfbVGJJ08Snw0Hy8pom1AqCeZxndX5r0LriIhmnLrh2HN6nwSkR1wevhsD/Pf2494JBmMk08drF+WaC6r4mNVfWp9IcV+VO962IlK2Eej+rZdxBRu98aiG9cNu2ACbufNptq1U20XLv4LAbp6M6lAMpfhCVmZXvnB6wAX04Rt9PFiRgG/ROhp+1Ee1Y36p493wFT8DwqONHSIAZmvLmc1ML0ESS3zuBx5HqUQRIcieApNArDre8NHL+EAL92kmsSyBlgicfzHGYxz3kbs2Pnfkfg+24Qc8vSBDKibv5rPwTcg==
  template:
    metadata:
      name: litellm-gemini-api-key-secret
      namespace: litellm
    type: Opaque
