apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-pvc
  namespace: frigate
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  selector:
    matchLabels:
      app: frigate
