apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: headlamp-ingressroute
  namespace: kube-system
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`headlamp.homelab.rivetcode.com`)
    kind: Rule
    services:
    - name: headlamp
      port: 80
