apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: config-boardgames
  namespace: kube-system
spec:
  interval: 5m
  dependsOn:
  - name: bgg-inventory-nextjs
  path: ./configs/
  prune: true # remove any elements later removed from the above path
  timeout: 2m
  sourceRef:
    kind: GitRepository
    name: boardgames-configs
  retryInterval: 1m
