apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bgg-inventory-nextjs
  namespace: boardgames
spec:
  interval: 5m
  chart:
    spec:
      chart: ./chart  # relative path in the repo
      sourceRef:
        kind: GitRepository
        name: bgg-inventory-nextjs
        namespace: flux-system
  values:
    # optional custom values here
