apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bgg-inventory-nextjs
  namespace: boardgames
spec:
  interval: 5m
  chart:
    spec:
      chart: ./chart  # relative path in the repo
      sourceRef:
        kind: GitRepository
        name: bgg-inventory-nextjs
        namespace: flux-system
  # https://github.com/firefly2442/bgg-inventory-nextjs/blob/master/chart/values.yaml
  values:
    image:
      repository: harbor.homelab.rivetcode.com/ghcr-proxy/firefly2442/bgg-inventory-nextjs
