apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vscode-cert
  namespace: vscode
spec:
  secretName: vscode-certificate-secret
  dnsNames:
    - "vscode.homelab.rivetcode.com"
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
