apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: rabbitmq
  labels:
    app.kubernetes.io/name: rabbitmq
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: rabbitmq
  ports:
    - name: rabbitmq-http
      port: 15672
      targetPort: http
      protocol: TCP
    - name: rabbitmq-amqp
      port: 5672
      targetPort: amqp
      protocol: TCP
    - name: rabbitmq-mqtt
      port: 1883
      targetPort: mqtt
      protocol: TCP
