apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: vscode
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/firefly2442/docker-vscode-customized
  ref:
    branch: master
