---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-admin-password-secret
  namespace: harbor
spec:
  encryptedData:
    HARBOR_ADMIN_PASSWORD: AgCrjBU2DwUxbmMWMNvPtX3bI/+k022WaaQIQz3EdbSTx41bHfDafuHxI5f/ualPSPDqZkJp23+3eCOIWG2RAc6tTCrkelJ6j/+zF/hKUBl7el7QWRVxo/VVaLeY8w/mkYz1KhWPRJHbo3UjNsW0CIfaaJ5r9wB7OPTXRSL11mp0zZtnh9lvpkhHKhxgCJ3wq3Xt4dBhSK1aTE1wSRme0b7T0g30SvgYAXwHP/ZHSwLhcQwzM5yRk+tdovsKqaQWNwUjyAmHenhv82dFbfi3RQ4MQ0/xNMYaA1JRf8PzcK1Pg41gj+w7A1DzuQ54yXMXDFHLR2pAYwsEZzKCcR0nlzqSVsG2skpdOIcsDQab53IuC2LY50HsFjeP2aPJ5r4EnESF9yPgHwN/U99d15yQbweu9lP1p2pUQT5uU0XOT0zqrNu5EonLwhtULF8oxCWtaZ5CiAxcEDrAxNBcEGYZiMBUzXttnRBrGMs6yMFyH4DEidKTShuyd//X5byFAkBoHJ4yUOZjYkfAiylgQMaxgEASF7dmKRYczICVasgS14vWSV+a0oUy8j2rvhfTvrHXqgYQXZQ98BBII3qj0PWyGdIq8Exbac4A87XbCp20jSoJp9nb1iQ59PzUsJg25tqqoUl6nnUx2f8me13w8jb1GqylDUaCd+XZptsNxZPgQ/CresLrQYx7yKRIFavkmBJ8MEXPkEoeNHsGIw==
  template:
    metadata:
      name: harbor-admin-password-secret
      namespace: harbor
    type: Opaque
