---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-s3-credentials-secret
  namespace: harbor
spec:
  encryptedData:
    REGISTRY_STORAGE_S3_ACCESSKEY: AgCqRRo+1+2R3rDw4oxQ263BEjytjjjc1s0W56NL0o4JKvg7IXPrHrUrfxxGI2zZyF533D0tBXHJYgfKlP+MQPjOwVIGT3+qARH/EwGY36piiDwGytaLT2oNhobzmU8HrCVyrOEfjamNrs/h9IHGQ70krWJ+XYBwvWlgTdlMeHRIO8O+tNN9N3fWFTfOvlC9K4ixcKcwu+HV7g8v0AMCGSOKObg251IYMIdNumZWocnunmFeL6wXdreyUbox2n7tcoUyg/6G1hUbZz+hSfcgpkiikZF+NRFwT6+MphpVFZNGEaDMxh3AzIQ94TyWGNpE+zXcEdqqsgkVa7YknQsMKs05I1OWqy+iapLcgnc5lW6VZ6li+fuSmh1fsFOAfvpd4s2Z8T39eVQmJTrsPDdAWVeHRJLOxsaAeXGrEaPFJBpRHQuiiV9+uQWG/jn2P9LW5VGBcdzsNW38YPvZ1phPmV2wyQ/FU92qk8YxUeV9hWL0DPuUJ9abLeFx76S9YbmuLhYemD5xnUqHGe2N5ZkgYCfOIS04YtmQDVNZGll1tqws2jND9+rEyNPsbdKQ/75nZ75w+1/pUaNQAHxDzuMqRyCzi6upVm4gmIfLL57rjPHl3TRYIjs6uCRjKU3ikSNRgAWZh2GWc6F/yqM0nnaHjYDjOFOsEFwYf4dJn09fggsPjORlYccGcVfIfDe+UU4ptcPp4fAfjw==
    REGISTRY_STORAGE_S3_SECRETKEY: AgC1qlkPFIMGsyvInXUC0ZTnQc11SvVsGX3FoJq9q0H0c1af5LlsYu7HRwA0zZzmaH/jjxjGkpAhaQgFk45r2qb1cwdooPYgywID0bCab+CJgP2Ix8bZvZ4lkkFCo2uGqrE8NvJGH53HIXV3hJyLOm9D1vb0Q9q97f38GQYkBb+EXSZszE0rYu/aMbYUx6TsS4tQP2E8WkfCNtc3055wLhVsX1itpLctozW5kD5wdycLlrc5WQ9R16DMwRIl5hkLzDOH8OmHylCcNvdftVWKkZybZo0uaKDnj7r6mcePS2FSuVL5fAUWEFenVC4X87cHelzwKCw59E/rgPSMWM+HJqPbvd28VUycnJxKnWBMnDNqls1CLbiKoNij45QdOSGjz2za7SNl30q7y9ChdSQm9zdZMZHBGhouSedckaIk3QARvdTl6xasWDDOcJJyyyExQ4RSZ1UWbF/Gs16uts2TGDu0pVJ+b4lWH/BN/BqwnEnZlx3DLC7w3BpSG/iS5JmHdFMUwrXnGiazxgs4ticXE8BB7510Pw64INVcssZ3WkAxA90vYSQMgb3RrAD9/t9CBY+3nyivL+p3E7lYQF9kg2El2d6Qh/DiOeyEEPa64lNTvFJaA9TSMLktfqH/sDLKST4iXhJIwjpKXcMAzs7KuGh07NLbn/O1MtWVlDJYrb9aqijOO+bOjBj43ftGFwq3VHTVpnnQaS4=
  template:
    metadata:
      name: harbor-s3-credentials-secret
      namespace: harbor
    type: Opaque
