apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rancher
  namespace: cattle-system
spec:
  interval: 5m
  chart:
    spec:
      chart: rancher
      # https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/rancher-v2-10-3/
      # rancher only supports specific versions of Kubernetes
      version: '2.12.3'
      sourceRef:
        kind: HelmRepository
        name: rancher
        namespace: flux-system
      interval: 5m
  values:
    type: LoadBalancer
