apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kuberay-operator
  namespace: kuberay-operator
spec:
  interval: 5m
  chart:
    spec:
      chart: kuberay-operator
      # https://ray-project.github.io/kuberay-helm/index.yaml
      # https://docs.ray.io/en/latest/cluster/kubernetes/getting-started/kuberay-operator-installation.html
      # https://ray-project.github.io/kuberay/deploy/installation/
      # https://github.com/ray-project/kuberay
      # https://github.com/ray-project/kuberay/tree/master/helm-chart/kuberay-operator
      version: '1.5.0' # this should match the tag below
      sourceRef:
        kind: HelmRepository
        name: kuberay-operator-repo
        namespace: flux-system
      interval: 5m
  install:
    crds: CreateReplace
  # https://github.com/ray-project/kuberay/blob/master/helm-chart/kuberay-operator/values.yaml
  values:
    metrics:
      # -- Whether KubeRay operator should emit control plane metrics.
      enabled: true
    image:
      repository: "quay.io/kuberay/operator"
      tag: "v1.5.0"
    env:
      # https://docs.ray.io/en/latest/cluster/usage-stats.html
      - name: RAY_USAGE_STATS_ENABLED
        value: 0
