apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media
  namespace: jellyfin
spec:
  storageClassName: local-path
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 15Ti
