apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-media
  namespace: jellyfin
spec:
  capacity:
    storage: 15Ti
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: jellyfin-media-local
  local:
    path: /twotbmirror/media/
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - alienware
