apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media
  namespace: jellyfin
spec:
  storageClassName: jellyfin-media-local
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 15Ti
