apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-setup-script
  namespace: authentik
data:
  setup-authentik.py: |
    # contents of the python file here (can be auto-filled from your script)
