apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: authentik-ingressroute
  namespace: authentik
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-clusterissuer
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`authentik.homelab.rivetcode.com`)
    kind: Rule
    services:
    - name: authentik-server
      port: 80
  tls:
    secretName: authentik-certificate-secret
