apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: photoprism
  namespace: photoprism
spec:
  interval: 5m
  chart:
    spec:
      chart: photoprism
      version: '2.0.0'
      sourceRef:
        kind: HelmRepository
        name: photoprism
        namespace: flux-system
      interval: 5m
  # https://github.com/p80n/photoprism-helm/blob/main/values.yaml
  #values:
