apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: photoprism
  namespace: photoprism
spec:
  interval: 30m
  chart:
    spec:
      chart: ./   # path inside the repo
      sourceRef:
        kind: GitRepository
        name: photoprism
        namespace: flux-system
