apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: photoprism
  namespace: photoprism
spec:
  interval: 5m
  chart:
    spec:
      # https://artifacthub.io/packages/helm/andrenarchy/photoprism
      chart: photoprism
      version: '8.10.0'
      sourceRef:
        kind: HelmRepository
        name: photoprism
        namespace: flux-system
      interval: 5m
  values:
    persistence:
      config:
        enabled: true
        mountPath: /photoprism/storage
      originals:
        enabled: true
        mountPath: "/photoprism/originals"
    env:
      PHOTOPRISM_PUBLIC: "true"
