apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: photoprism
  namespace: photoprism
spec:
  interval: 5m
  chart:
    spec:
      chart: photoprism
      version: 30.20.1
      sourceRef:
        kind: HelmRepository
        name: photoprism
        namespace: flux-system
      interval: 5m
  # https://github.com/trueforge-org/truecharts/blob/master/charts/stable/photoprism/values.yaml
  values:
    image:
      repository: harbor.homelab.rivetcode.com/dockerhub-proxy/photoprism/photoprism
      pullPolicy: IfNotPresent
      # https://hub.docker.com/r/photoprism/photoprism/tags
      tag: "260919"
    resources:
      requests:
        memory: 1Gi
      limits:
        memory: 8Gi
    persistence:
      # Main storage (database, cache, sidecar data)
      storage:
        enabled: true
        size: 50Gi
        storageClass: longhorn-ha-3
        labels:
          recurring-job.longhorn.io/source: enabled
          recurring-job-group.longhorn.io/backup: enabled
      # Originals (where photos are stored)
      originals:
        enabled: true
        size: 250Gi
        storageClass: longhorn-ha-3
        labels:
          recurring-job.longhorn.io/source: enabled
          recurring-job-group.longhorn.io/backup: enabled
      # Imports (temporary import folder)
      import:
        enabled: true
        size: 25Gi
        storageClass: longhorn-ha-2
        labels:
          recurring-job.longhorn.io/source: enabled
          recurring-job-group.longhorn.io/backup: enabled
    # https://github.com/trueforge-org/truecharts/blob/master/charts/stable/mariadb/values.yaml
    mariadb:
      enabled: true
      persistence:
        data:
          enabled: true
          size: 5Gi
          storageClass: longhorn-ha-3
          labels:
            recurring-job.longhorn.io/source: enabled
            recurring-job-group.longhorn.io/backup: enabled
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                PHOTOPRISM_OIDC_URI: "https://authentik.homelab.rivetcode.com/application/o/photoprism/"
                PHOTOPRISM_OIDC_PROVIDER: "Authentik"
                PHOTOPRISM_OIDC_REDIRECT: "true"
                # allow new users to create an account when they sign in with OpenID Connect
                PHOTOPRISM_OIDC_REGISTER: "true"
                PHOTOPRISM_OIDC_CLIENT:
                  secretKeyRef:
                    name: photoprism-oauth-oidc-secret
                    key: PHOTOPRISM_OIDC_CLIENT
                PHOTOPRISM_OIDC_SECRET:
                  secretKeyRef:
                    name: photoprism-oauth-oidc-secret
                    key: PHOTOPRISM_OIDC_SECRET
