apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: photoprism
  namespace: photoprism
spec:
  interval: 5m
  chart:
    spec:
      chart: ./   # path inside the repo
      sourceRef:
        kind: GitRepository
        name: photoprism
        namespace: flux-system
  values:
    env:
      # warning, this opens your deployment up to anyone, be careful!
      # we're protecting the endpoint with Authentik so we're OK
      - name: PHOTOPRISM_AUTH_MODE
        value: "public"
