apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: navidrome-music
  namespace: navidrome
spec:
  storageClassName: nfs-navidrome-music
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 50Gi
