apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: defectdojo-cert
  namespace: defectdojo
spec:
  secretName: defectdojo-certificate-secret
  dnsNames:
    - "defectdojo.homelab.rivetcode.com"
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
