---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: frigate-rtsp-secret
  namespace: frigate
spec:
  encryptedData:
    FRIGATE_RTSP_PASSWORD: AgAZ+SVs+r3ZCas4Nea5wPSaiTmugnbGBqkQEaTDvkeRCKZzyr/n1Ex0ItaSCFVZ8QHyAGsKBzBWVLQkLkm7Tgb+/oG1PpcmX5/G/+2fTmG/Fb2n5CK+7owKbfis4PQpe1dIezQAO/fkQdxqG+tDqP/mQvvOciWvNv+5yEV24gwu6StR2C0AwVnvhdWAy+4mzZho6TKE4kMIvB9PrkK+HUTq1r8qSg2+yGWJqMUI1QwKsN9f7ZLRJxQKk5Mg1NVYod5XhSBmvIXf4sbMUOzmXkfRInspd5tdrR/xAgrvKRx8LyeobVwhYzAYF+ipWCreAYNJqCvSHL/sdp4jclY5+g30F9s7FpUiPhRjXy+8kx2fxI0Sb7LXm85qP1dJn2bHO4vwtufuHRkx4zVEluoPef7wcUUSfJy9XcvOZXInJcfUOecxzifzSlnJjcPh2fBmtF0OJEMW4XNPG5qAmmNaJiC/047htjeEd92stBHPdJbA+39Ce0HYCCtBnrWNlOe9Mt1/+0iBI94dYjK8HOTs/Z1GKobYyxSTJfc33bbQs1guMBLtNviShbz+eQ72D3bqUK9K+mYhxAowo5GTiWO1JzfKR9DK8cecc9zETsG6IrD6nHMQEacxmhAAA96gTc4D5U9cHeR8WMotbJpxEg8rHGzjF4+lPUyH3F02eTMqg9JdQ2D2yLCIYcJ3xN2W8mppPeNyDb6vCbra6Q==
  template:
    metadata:
      name: frigate-rtsp-secret
      namespace: frigate
    type: Opaque
