---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: frigate-rtsp-secret
  namespace: frigate
spec:
  encryptedData:
    FRIGATE_RTSP_PASSWORD: AgB3mFm3mSlSQ882LUTmxv6FSrtBSClxn1QSSKODsL8UQR1jmsLgD+b6rCXdBFwah1A5fJ9ekWYkO1fwwCYaHUCj0eohAMdFBgPDsMrymEGdnuQ8q+2lGPyzpClqJYJV5rDnmg+XeIrtjCVGJ82C2jFWu4cq46WhALxbmauTEKCt9lOLI16S7WH2x2uYEv96kZS9rtjGG62XZ5cQarhAiEgL/UFXIUv9sTi4CkJlHy0FnkQ2Q9f/VDzDKUvzSkisa/iPmLzjSKcnl6AJNXeMgiRdVch5yRiNwlOZWU7yVFKjxrM9OV0ZOJsGoS8dFUqRl1sQ4pMT/IKLI5Lhi9TIJPWVKQgqDNpar4hnNPCd/oModEI1yIwyTB/qRrLoP72cRBnGBWRs/ALvDJH68e6Ih5f9h5po+1rm5mrp6Dg3Lj0PSQDUcRfnA+PkOc3DIiISK1D/Vt/d/0QOyILP4sm+oNNGbGiwUkRysDA+tGTupHxCbXnvpcUUIb5BnWBkcVEQJcAC1ytgl06gvw2js3SiSSyjWNObDmA8UcGNYuqOdN/wcE6WbXETD4xNyGQOMAiIoNLgCzPFSFNiBmhad6ROvsBj7ASZoN0OKT4Tbpfzhgvh4oPXAf7BlP5CfBwHWo6vLsVDiZUtTRba96eGl3hQFiEYF2+yfgzgu4yogDm+7GMOasYisCK8wJcGHjjtK3p7xbjM2fD3qoVfWA==
  template:
    metadata:
      name: frigate-rtsp-secret
      namespace: frigate
    type: Opaque
