apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 5m
  chart:
    spec:
      chart: metallb
      # https://metallb.github.io/frr-k8s/index.yaml
      version: "0.14.9"
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
      interval: 5m
  install:
    crds: CreateReplace
  # https://github.com/metallb/metallb/blob/main/charts/metallb/values.yaml
  values:
    prometheus:
      namespace: prometheus
