apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-ip
  namespace: kube-system
spec:
  interval: 10m
  dependsOn:
  - name: metallb
  path: ./ip/
  prune: true # remove any elements later removed from the above path
  timeout: 2m
  sourceRef:
    kind: GitRepository
    name: metallb-ip
  retryInterval: 1m
