apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-ip-config
  namespace: flux-system
spec:
  targetNamespace: metallb-system
  path: ./clusters/home/apps/metallb-system/ip
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  interval: 10m
  dependsOn:
    - name: metallb-metallb-system
