apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: metallb-charts-git
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/metallb/metallb
  ref:
    branch: main
  ignore: |
    # exclude all but the CDRs
    /*
    # path to crds
    !/charts/metallb/charts
